import {useEffect,useState,type FormEvent} from 'react';
import {Check,MapPin,Images,Users,Star,RefreshCw,Plus,Repeat} from 'lucide-react';
import {Card,CardHeader,CardTitle,CardDescription,CardContent,CardFooter} from '@/components/ui/card';
import {Field,FieldGroup,FieldLabel,FieldDescription,FieldSet,FieldLegend} from '@/components/ui/field';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Button} from '@/components/ui/button';
import {Switch} from '@/components/ui/switch';
import {Checkbox} from '@/components/ui/checkbox';
import {Alert,AlertDescription} from '@/components/ui/alert';
import {Badge} from '@/components/ui/badge';
import {Skeleton} from '@/components/ui/skeleton';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectGroup,SelectItem} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {ArenaImagePicker} from '@/components/ArenaImagePicker';
import {api} from '@/lib/api';
import {errorMessage} from '@/lib/format';

type Settings={groupId:string;groupEnabled:boolean;events:string[];reviewEnabled:boolean;reviewDelayMinutes:number;reviewMessage:string;manualResumeOnly:boolean;monthlyChargeMessage:string};
type Arena={nome:string;address:string;addressNumber:string;district:string;city:string;state:string;mapsUrl:string;instagramUrl:string;reviewUrl:string};
type Court={id:string;name:string;photos:string[]};
type Data={settings:Settings;arena:Arena;courts:Court[]};
type Group={id:string;name:string};
type Delivery={id:string;kind:string;status:string;createdAt:string;error:string};
const events=[['pending','Nova reserva'],['confirmed','Reserva confirmada'],['paid','Pagamento recebido'],['cancelled','Cancelamento'],['expired','Reserva expirada'],['handoff','Atendimento humano']] as const;
const statuses:Record<string,string>={pending:'Aguardando',sending:'Enviando',sent:'Enviado',failed:'Falhou',unknown:'Conferir entrega',skipped:'Não enviado'};
export function WhatsAppServices({editable}:{editable:boolean}){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[groups,setGroups]=useState<Group[]>([]),[page,setPage]=useState(0),[more,setMore]=useState(false),[groupBusy,setGroupBusy]=useState(false),[createOpen,setCreateOpen]=useState(false),[groupName,setGroupName]=useState('Avisos da arena'),[participants,setParticipants]=useState(''),[deliveries,setDeliveries]=useState<Delivery[]>([]);
 async function load(){try{const result=await api<Data>('/api/whatsapp/services');setData(result);await refreshDeliveries();}catch(e){setError(errorMessage(e));}}
 async function refreshDeliveries(){try{setDeliveries((await api<{deliveries:Delivery[]}>('/api/whatsapp/deliveries')).deliveries);}catch(e){setError(errorMessage(e));}}
 useEffect(()=>{void load();},[]);
 const setting=<K extends keyof Settings>(key:K,value:Settings[K])=>setData(d=>d?{...d,settings:{...d.settings,[key]:value}}:d);
 const arena=(key:keyof Arena,value:string)=>setData(d=>d?{...d,arena:{...d.arena,[key]:value}}:d);
 async function save(e:FormEvent){e.preventDefault();if(!data)return;setBusy(true);setError('');setNotice('');try{await api('/api/whatsapp/services',{method:'PUT',body:JSON.stringify({arena:data.arena,settings:data.settings})});setNotice('Informações e automações salvas.');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 async function loadGroups(next=0){setGroupBusy(true);setError('');try{const result=await api<{groups:Group[];hasMore:boolean}>(`/api/whatsapp/groups?page=${next}`);setGroups(old=>next?[...old,...result.groups.filter(g=>!old.some(o=>o.id===g.id))]:result.groups);setPage(next);setMore(result.hasMore);}catch(e){setError(errorMessage(e));}finally{setGroupBusy(false);}}
 async function createGroup(e:FormEvent){e.preventDefault();setGroupBusy(true);setError('');try{const group=await api<Group>('/api/whatsapp/groups',{method:'POST',body:JSON.stringify({name:groupName,participants:participants.split(/[\n,;]/).map(p=>p.replace(/\D/g,'')).filter(Boolean)})});setGroups(old=>[group,...old.filter(g=>g.id!==group.id)]);setting('groupId',group.id);setCreateOpen(false);setNotice('Grupo criado. Ative os avisos e salve as configurações.');}catch(e){setError(errorMessage(e));}finally{setGroupBusy(false);}}
 async function photos(court:Court,images:string[]){setBusy(true);setError('');try{await api(`/api/whatsapp/courts/${court.id}/photos`,{method:'PUT',body:JSON.stringify({photos:images})});setData(d=>d?{...d,courts:d.courts.map(c=>c.id===court.id?{...c,photos:images}:c)}:d);setNotice(`Fotos de ${court.name} salvas.`);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 if(!data)return <div className="flex flex-col gap-4">{error?<Alert variant="destructive"><AlertDescription>{error}<Button variant="outline" onClick={()=>void load()}>Tentar novamente</Button></AlertDescription></Alert>:<><Skeleton className="h-48 w-full"/><Skeleton className="h-48 w-full"/></>}</div>;
 const disabled=!editable||busy;
 return <div className="flex min-w-0 flex-col gap-5">
 {error&&<Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}
 {notice&&<Alert role="status"><AlertDescription>{notice}</AlertDescription></Alert>}
 <form id="whatsapp-services" onSubmit={e=>void save(e)} className="flex flex-col gap-5">
 <Card><CardHeader><CardTitle className="flex items-center gap-2"><MapPin/>Informações da arena</CardTitle><CardDescription>O agente consulta estes dados quando o cliente pergunta. O endereço é compartilhado com o cadastro da arena.</CardDescription></CardHeader><CardContent><FieldGroup>
 <div className="grid gap-4 sm:grid-cols-2">{([['address','Endereço'],['addressNumber','Número'],['district','Bairro'],['city','Cidade'],['state','UF']] as const).map(([key,label])=><Field key={key}><FieldLabel htmlFor={`arena-${key}`}>{label}</FieldLabel><Input id={`arena-${key}`} disabled={disabled} maxLength={key==='state'?2:180} required={['address','city','state'].includes(key)} value={data.arena[key]} onChange={e=>arena(key,key==='state'?e.target.value.toUpperCase():e.target.value)}/></Field>)}</div>
 {([['mapsUrl','Localização no Google Maps','https://maps.app.goo.gl/…'],['instagramUrl','Instagram da arena','https://www.instagram.com/suaarena/'],['reviewUrl','Link para avaliar no Google','https://g.page/r/…/review']] as const).map(([key,label,placeholder])=><Field key={key}><FieldLabel htmlFor={`arena-${key}`}>{label}</FieldLabel><Input id={`arena-${key}`} type="url" maxLength={1000} disabled={disabled} value={data.arena[key]} placeholder={placeholder} onChange={e=>arena(key,e.target.value)}/></Field>)}
 </FieldGroup></CardContent></Card>
 <Card><CardHeader><CardTitle className="flex items-center gap-2"><Users/>Grupo de avisos</CardTitle><CardDescription>Receba os acontecimentos da arena em um grupo da equipe.</CardDescription></CardHeader><CardContent><FieldGroup>
 <Field orientation="horizontal"><Switch id="group-enabled" disabled={disabled} checked={data.settings.groupEnabled} onCheckedChange={v=>setting('groupEnabled',v)}/><FieldLabel htmlFor="group-enabled">Enviar avisos para a equipe</FieldLabel></Field>
 <Field><FieldLabel htmlFor="notice-group">Grupo de destino</FieldLabel><Select disabled={disabled} value={data.settings.groupId||'none'} onValueChange={v=>setting('groupId',v==='none'?'':v)}><SelectTrigger id="notice-group" className="w-full"><SelectValue placeholder="Selecione um grupo"/></SelectTrigger><SelectContent><SelectGroup><SelectItem value="none">Nenhum grupo</SelectItem>{data.settings.groupId&&!groups.some(g=>g.id===data.settings.groupId)&&<SelectItem value={data.settings.groupId}>Grupo configurado</SelectItem>}{groups.map(g=><SelectItem key={g.id} value={g.id}>{g.name}</SelectItem>)}</SelectGroup></SelectContent></Select><FieldDescription>O número conectado precisa participar do grupo e ter permissão para enviar mensagens.</FieldDescription></Field>
 <div className="flex flex-wrap gap-2"><Button type="button" variant="outline" disabled={disabled||groupBusy} onClick={()=>void loadGroups()}><RefreshCw data-icon="inline-start"/>Carregar grupos</Button>{more&&<Button type="button" variant="outline" disabled={groupBusy} onClick={()=>void loadGroups(page+1)}>Mais grupos</Button>}<Button type="button" variant="outline" disabled={disabled||groupBusy} onClick={()=>setCreateOpen(true)}><Plus data-icon="inline-start"/>Criar grupo</Button></div>
 <FieldSet><FieldLegend>Avisar sobre</FieldLegend><FieldGroup>{events.map(([key,label])=><Field key={key} orientation="horizontal"><Checkbox id={`event-${key}`} disabled={disabled} checked={data.settings.events.includes(key)} onCheckedChange={checked=>setting('events',checked?[...data.settings.events,key]:data.settings.events.filter(e=>e!==key))}/><FieldLabel htmlFor={`event-${key}`}>{label}</FieldLabel></Field>)}</FieldGroup></FieldSet>
 </FieldGroup></CardContent></Card>
 <Card><CardHeader><CardTitle className="flex items-center gap-2"><Repeat/>Cobrança de mensalistas</CardTitle><CardDescription>Enviada no dia do vencimento, às 9h, para os planos com “Cobrar automaticamente no WhatsApp” ligado (em Mensalistas). Uma mensagem por mensalidade; quem já pagou não recebe.</CardDescription></CardHeader><CardContent><FieldGroup>
 <Field><FieldLabel htmlFor="monthly-charge-message">Mensagem</FieldLabel><Textarea id="monthly-charge-message" rows={4} maxLength={1200} required disabled={disabled} value={data.settings.monthlyChargeMessage} onChange={e=>setting('monthlyChargeMessage',e.target.value)}/><FieldDescription>Use {'{nome}'}, {'{valor}'}, {'{vencimento}'}, {'{mes}'} e {'{arena_name}'}.</FieldDescription></Field>
 <Alert><AlertDescription><strong>Prévia</strong><p className="whitespace-pre-wrap break-words">{data.settings.monthlyChargeMessage.replaceAll('{nome}','Isaque').replaceAll('{arena_name}',data.arena.nome).replaceAll('{valor}','R$ 400,00').replaceAll('{vencimento}','10/11/2026').replaceAll('{mes}','novembro')}</p></AlertDescription></Alert>
 </FieldGroup></CardContent></Card>
 <Card><CardHeader><CardTitle className="flex items-center gap-2"><Star/>Avaliação após o jogo</CardTitle><CardDescription>Convide o cliente a avaliar a arena depois do término da reserva.</CardDescription></CardHeader><CardContent><FieldGroup>
 <Field orientation="horizontal"><Switch id="review-enabled" disabled={disabled} checked={data.settings.reviewEnabled} onCheckedChange={v=>setting('reviewEnabled',v)}/><FieldLabel htmlFor="review-enabled">Pedir avaliação automaticamente</FieldLabel></Field>
 <Field><FieldLabel htmlFor="review-delay">Minutos após o fim do jogo</FieldLabel><Input id="review-delay" type="number" min={0} max={1440} required className="max-w-40" disabled={disabled} value={data.settings.reviewDelayMinutes} onChange={e=>setting('reviewDelayMinutes',Number(e.target.value))}/><FieldDescription>Somente reservas confirmadas ou concluídas. Canceladas e pendentes não recebem o pedido.</FieldDescription></Field>
 <Field><FieldLabel htmlFor="review-message">Mensagem</FieldLabel><Textarea id="review-message" rows={4} maxLength={1200} required disabled={disabled} value={data.settings.reviewMessage} onChange={e=>setting('reviewMessage',e.target.value)}/><FieldDescription>Variáveis: {'{nome}'}, {'{arena_name}'} e {'{review_link}'}. Inclua o link na mensagem.</FieldDescription></Field>
 <Alert><AlertDescription><strong>Prévia</strong><p className="whitespace-pre-wrap break-words">{data.settings.reviewMessage.replaceAll('{nome}','Isaque').replaceAll('{arena_name}',data.arena.nome).replaceAll('{review_link}',data.arena.reviewUrl||'[Link de avaliação]')}</p></AlertDescription></Alert>
 </FieldGroup></CardContent><CardFooter><Button type="submit" className="w-full sm:w-auto" disabled={disabled||uploading||groupBusy}><Check data-icon="inline-start"/>{busy?'Salvando…':'Salvar informações e automações'}</Button></CardFooter></Card>
 </form>
 <Card><CardHeader><CardTitle className="flex items-center gap-2"><Images/>Fotos das quadras</CardTitle><CardDescription>O bot envia estas imagens quando o cliente pedir. As alterações na galeria são salvas imediatamente.</CardDescription></CardHeader><CardContent className="flex flex-col gap-6">{data.courts.length?data.courts.map(c=><ArenaImagePicker key={c.id} label={c.name} images={c.photos} maxImages={6} disabled={disabled||uploading} onBusyChange={setUploading} onChange={images=>void photos(c,images)}/>):<p className="text-sm text-muted-foreground">Cadastre uma quadra para adicionar suas fotos.</p>}</CardContent></Card>
 <Card><CardHeader><CardTitle>Envios recentes</CardTitle><CardDescription>Se aparecer “Conferir entrega”, veja a conversa no WhatsApp antes de repetir o envio.</CardDescription></CardHeader><CardContent className="flex flex-col gap-3">{deliveries.length?deliveries.map(d=><div key={d.id} className="flex flex-wrap items-center justify-between gap-2 border-b pb-3"><div><p className="text-sm">{events.find(e=>e[0]===d.kind)?.[1]||({review:'Pedido de avaliação',photo:'Foto da quadra',monthly_charge:'Cobrança de mensalidade'} as Record<string,string>)[d.kind]||d.kind}</p><p className="text-xs text-muted-foreground">{new Date(d.createdAt).toLocaleString('pt-BR')}</p>{d.error&&<p className="text-xs text-muted-foreground">{d.error}</p>}</div><Badge variant={['failed','unknown'].includes(d.status)?'destructive':'secondary'}>{statuses[d.status]||d.status}</Badge></div>):<p className="text-sm text-muted-foreground">Os próximos avisos, fotos e pedidos de avaliação aparecerão aqui.</p>}</CardContent><CardFooter><Button type="button" variant="outline" onClick={()=>void refreshDeliveries()}>Atualizar envios</Button></CardFooter></Card>
 <Dialog open={createOpen} onOpenChange={v=>{if(!groupBusy)setCreateOpen(v);}}><DialogContent><form onSubmit={e=>void createGroup(e)} className="flex flex-col gap-5"><DialogHeader><DialogTitle>Criar grupo de avisos</DialogTitle><DialogDescription>O grupo será criado no WhatsApp conectado. Confira os participantes antes de continuar.</DialogDescription></DialogHeader><FieldGroup><Field><FieldLabel htmlFor="group-name">Nome do grupo</FieldLabel><Input id="group-name" required minLength={3} maxLength={80} value={groupName} onChange={e=>setGroupName(e.target.value)}/></Field><Field><FieldLabel htmlFor="group-participants">Participantes</FieldLabel><Textarea id="group-participants" required rows={4} value={participants} onChange={e=>setParticipants(e.target.value)} placeholder="5594999999999"/><FieldDescription>Um telefone por linha, com DDI e DDD. Até 30 participantes.</FieldDescription></Field></FieldGroup>{error&&<Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}<DialogFooter><Button type="button" variant="outline" disabled={groupBusy} onClick={()=>setCreateOpen(false)}>Voltar</Button><Button disabled={groupBusy}>{groupBusy?'Criando…':'Criar grupo no WhatsApp'}</Button></DialogFooter></form></DialogContent></Dialog>
 </div>;
}
