import { randomUUID, randomBytes, scryptSync } from 'node:crypto';
import { and, asc, desc, eq } from 'drizzle-orm';
import type { FastifyInstance } from 'fastify';
import { appAudit, companies, companyHours, courts, users } from '@quadrasflow/database';
import { db } from './database.js';
import { fail, text } from './arena.js';
import type { AuthUser } from './auth.js';
const bodyOf=(req:{body?:unknown})=>(req.body||{}) as Record<string,unknown>;const actor=(req:FastifyRequest)=>{const user=(req as typeof req & {user:AuthUser|null}).user;if(!user)throw fail(401,'Entre na sua conta para continuar.');if(user.role!=='platform_admin')throw fail(403,'Acesso restrito à administração da plataforma.');return user;};
import type { FastifyRequest } from 'fastify';
function slugify(v:string){return v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,50)}
export async function registerPlatformRoutes(app:FastifyInstance){const auth={preHandler:app.authenticate};
 app.get('/api/platform/companies',auth,async req=>{actor(req);const list=await db.select().from(companies).orderBy(desc(companies.createdAt));return {companies:await Promise.all(list.map(async c=>{const [companyUsers,activeCourts]=await Promise.all([db.select().from(users).where(and(eq(users.companyId,c.id),eq(users.active,true))),db.select().from(courts).where(and(eq(courts.companyId,c.id),eq(courts.active,true)))]),admin=companyUsers.find(u=>u.role==='arena_admin');return {id:c.id,name:c.name,slug:c.slug,status:c.status,created_at:c.createdAt,users_count:companyUsers.length,courts_count:activeCourts.length,admin_name:admin?.name||null,admin_email:admin?.email||null,onboarding_completed:c.onboardingCompleted};}))};});
 app.post('/api/platform/companies',auth,async(req,reply)=>{const platform=actor(req),b=bodyOf(req),name=text(b.companyName,'o nome da empresa'),adminName=text(b.adminName,'o nome do administrador'),email=String(b.email||'').trim().toLowerCase(),password=String(b.password||''),slug=slugify(String(b.slug||name)),phone=String(b.phone||'').replace(/\D/g,'');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>254)throw fail(400,'Informe um e-mail válido.');if(password.length<8||password.length>200)throw fail(400,'A senha inicial deve ter pelo menos 8 caracteres.');if(!slug)throw fail(400,'Informe um identificador válido.');const id=randomUUID(),userId=randomUUID(),createdAt=new Date().toISOString(),salt=randomBytes(16).toString('hex'),passwordHash=scryptSync(password,salt,64).toString('hex');try{await db.transaction(async tx=>{await tx.insert(companies).values({id,name,slug,phone,status:'active',onboardingCompleted:false,createdAt,description:'',address:'',addressNumber:'',district:'',zipCode:'',city:'',state:'',amenities:[],photos:[],publicOptions:{},logoUrl:'',cancellationHours:24,cancellationFeePercent:0});await tx.insert(users).values({id:userId,companyId:id,name:adminName,email,passwordHash,passwordSalt:salt,role:'arena_admin',active:true,createdAt});await tx.insert(companyHours).values(Array.from({length:7},(_,weekday)=>({companyId:id,weekday,isOpen:true,openTime:'08:00',closeTime:'23:00'})));await tx.insert(appAudit).values({id:randomUUID(),companyId:null,userId:platform.id,action:'company.created',entity:'company',entityId:id,details:{slug},createdAt});});}catch(e){if((e as {code?:string}).code==='23505')throw fail(409,'Esse identificador ou e-mail já está cadastrado.');throw e;}return reply.code(201).send({company:{id,name,slug,status:'active',created_at:createdAt,onboarding_completed:false},admin:{name:adminName,email}});});
 app.patch('/api/platform/companies/:id/status',auth,async req=>{const platform=actor(req),{id}=req.params as {id:string},status=String(bodyOf(req).status||'');if(!['active','suspended'].includes(status))throw fail(400,'Status inválido.');const updated=await db.update(companies).set({status}).where(eq(companies.id,id)).returning({id:companies.id});if(!updated.length)throw fail(404,'Empresa não encontrada.');await db.insert(appAudit).values({id:randomUUID(),companyId:null,userId:platform.id,action:`company.${status}`,entity:'company',entityId:id,details:{},createdAt:new Date().toISOString()});return {ok:true};});
}
