import { createHash, randomUUID } from 'node:crypto';
import { and, asc, eq, gte, lt, ne, sql } from 'drizzle-orm';
import type { FastifyInstance } from 'fastify';
import { bookings, blockedSlots, clients, companies, companyHours, courts, monthlyMembers, reviewLinks, reviews, tournamentEntries, tournaments, companyPriceSlots } from '@quadrasflow/database';
import { db } from './database.js';
import { findMonthlyConflict } from './monthly-conflict.js';
import { bookingAmountCents } from './pricing.js';
import { attachPixStatusToken, createBookingPixCharge, PIX_MINUTES, publicPaymentPolicy, publicPixStatus } from './mercadopago.js';
import { changeBookingStatus } from './booking-finance.js';
import { freeStarts, toMinutes, type Busy } from './public-availability.js';
import { durationError, maxDurationOf } from './booking-duration.js';
import { fail, text } from './arena.js';
const bodyOf=(req:{body?:unknown})=>(req.body||{}) as Record<string,unknown>;const hash=(v:string)=>createHash('sha256').update(v).digest('hex');const digits=(v:unknown)=>String(v??'').replace(/\D/g,'');
function dayToday(){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo'}).format(new Date())}function nowTime(){return new Intl.DateTimeFormat('en-GB',{timeZone:'America/Sao_Paulo',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date())}function timeHH(n:number){return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}
export async function registerPublicRoutes(app:FastifyInstance){
 app.get('/api/public/arenas/:slug',async(req)=>{
  const {slug}=req.params as {slug:string},query=req.query as {date?:string},day=String(query.date||dayToday());if(!/^\d{4}-\d{2}-\d{2}$/.test(day)||Number.isNaN(Date.parse(`${day}T12:00:00Z`)))throw fail(400,'Data inválida.');
  const company=(await db.select().from(companies).where(and(eq(companies.slug,slug),eq(companies.status,'active'))).limit(1))[0];if(!company)throw fail(404,'Arena não encontrada.');
  const weekday=new Date(`${day}T12:00:00Z`).getUTCDay();const [cs,bs,blocked,members,hours,ts,prices]=await Promise.all([db.select({id:courts.id,name:courts.name,sport:courts.sport,price_cents:courts.priceCents,photo_url:courts.photoUrl}).from(courts).where(and(eq(courts.companyId,company.id),eq(courts.active,true))).orderBy(asc(courts.name)),db.select({court_id:bookings.courtId,start_at:bookings.startAt,end_at:bookings.endAt}).from(bookings).where(and(eq(bookings.companyId,company.id),ne(bookings.status,'cancelled'),gte(bookings.startAt,`${day}T00:00:00.000Z`),lt(bookings.startAt,`${day}T24:00:00.000Z`)),),db.select({court_id:blockedSlots.courtId,start_at:blockedSlots.startAt,end_at:blockedSlots.endAt}).from(blockedSlots).where(and(eq(blockedSlots.companyId,company.id),gte(blockedSlots.startAt,`${day}T00:00:00.000Z`),lt(blockedSlots.startAt,`${day}T24:00:00.000Z`)),),db.select().from(monthlyMembers).where(and(eq(monthlyMembers.companyId,company.id),eq(monthlyMembers.weekday,weekday),eq(monthlyMembers.status,'active'))),db.select().from(companyHours).where(and(eq(companyHours.companyId,company.id),eq(companyHours.weekday,weekday))).limit(1),db.select().from(tournaments).where(and(eq(tournaments.companyId,company.id),eq(tournaments.status,'open'))).orderBy(asc(tournaments.startDate)),db.select({weekday:companyPriceSlots.weekday,start_time:companyPriceSlots.startTime,end_time:companyPriceSlots.endTime,price_cents:companyPriceSlots.priceCents}).from(companyPriceSlots).where(eq(companyPriceSlots.companyId,company.id))]);
  const hour=hours[0]||{weekday,isOpen:true,openTime:'08:00',closeTime:'23:00'};for(const m of members){const n=Number(m.startTime.slice(0,2))*60+Number(m.startTime.slice(3));bs.push({court_id:m.courtId,start_at:`${day}T${m.startTime}:00.000Z`,end_at:`${day}T${timeHH(n+m.durationMinutes)}:00.000Z`});}
  const now=nowTime(),nowMin=Number(now.slice(0,2))*60+Number(now.slice(3)),openMin=Number(hour.openTime.slice(0,2))*60+Number(hour.openTime.slice(3)),closeMin=Number(hour.closeTime.slice(0,2))*60+Number(hour.closeTime.slice(3)),notBefore=hour.isOpen&&Math.max(openMin,day===dayToday()?Math.ceil(nowMin/30)*30:openMin)+60<=closeMin?timeHH(Math.max(openMin,day===dayToday()?Math.ceil(nowMin/30)*30:openMin)):'24:00';
  const options=company.publicOptions||{};const profile={description:company.description,address:company.address,city:company.city,state:company.state,amenities:company.amenities,photos:company.photos,logo_url:company.logoUrl,options};
  return {arena:{name:company.name,slug:company.slug,...profile,whatsapp:digits(company.phone)},max_duration_minutes:maxDurationOf(company.publicOptions),pix_minutes:PIX_MINUTES,courts:cs,bookings:bs,blocks:blocked,hours:{weekday,is_open:hour.isOpen?1:0,open_time:hour.openTime,close_time:hour.closeTime},tournaments:await Promise.all(ts.map(async t=>({id:t.id,name:t.name,sport:t.sport,category:t.category,start_date:t.startDate,entry_fee_cents:t.entryFeeCents,capacity:t.capacity,entries_count:(await db.select({id:tournamentEntries.id}).from(tournamentEntries).where(eq(tournamentEntries.tournamentId,t.id))).length}))),prices,not_before:notBefore,advance_payment:await publicPaymentPolicy(company.id)};
 });
 app.post('/api/public/arenas/:slug/bookings',{config:{rateLimit:{max:20,timeWindow:10*60*1000}}},async(req,reply)=>{
  const {slug}=req.params as {slug:string},b=bodyOf(req),company=(await db.select().from(companies).where(and(eq(companies.slug,slug),eq(companies.status,'active'))).limit(1))[0];if(!company)throw fail(404,'Arena não encontrada.');const name=text(b.customerName,'seu nome'),phone=digits(b.customerPhone),courtId=String(b.courtId||''),rawStart=String(b.startAt||''),rawEnd=String(b.endAt||''),startDate=new Date(rawStart),endDate=new Date(rawEnd);if(Number.isNaN(startDate.valueOf())||Number.isNaN(endDate.valueOf()))throw fail(400,'Escolha uma data e um horário válidos.');const startAt=startDate.toISOString(),endAt=endDate.toISOString(),start=Date.parse(startAt),end=Date.parse(endAt),today=dayToday(),last=new Date(`${today}T12:00:00Z`);last.setUTCDate(last.getUTCDate()+90);if(phone.length<10||phone.length>15)throw fail(400,'Informe um WhatsApp válido com DDD.');const policy=await publicPaymentPolicy(company.id),email=String(b.customerEmail||'').trim().toLowerCase();if(policy&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw fail(400,'Informe um e-mail válido para gerar o Pix.');if(startAt.slice(0,10)!==endAt.slice(0,10)||start%1800000||end-start<3600000||(end-start)%1800000||startAt.slice(0,10)<today||startAt.slice(0,10)>last.toISOString().slice(0,10)||(startAt.slice(0,10)===today&&startAt.slice(11,16)<=nowTime()))throw fail(400,'Escolha um horário futuro disponível entre hoje e os próximos 90 dias.');if(end-start>maxDurationOf(company.publicOptions)*60000)throw fail(400,durationError(maxDurationOf(company.publicOptions)));
  const result=await db.transaction(async tx=>{await tx.execute(sql`SELECT pg_advisory_xact_lock(hashtext(${company.id}),hashtext(${courtId}))`);const court=(await tx.select().from(courts).where(and(eq(courts.id,courtId),eq(courts.companyId,company.id),eq(courts.active,true))).limit(1))[0];if(!court)throw fail(404,'A quadra não está disponível.');const weekday=new Date(`${startAt.slice(0,10)}T12:00:00Z`).getUTCDay(),hours=(await tx.select().from(companyHours).where(and(eq(companyHours.companyId,company.id),eq(companyHours.weekday,weekday))).limit(1))[0];if(!hours?.isOpen||startAt.slice(11,16)<hours.openTime||endAt.slice(11,16)>hours.closeTime)throw fail(400,'A arena está fechada nesse horário.');const [conflict,block]=await Promise.all([tx.select({id:bookings.id}).from(bookings).where(and(eq(bookings.companyId,company.id),eq(bookings.courtId,courtId),ne(bookings.status,'cancelled'),sql`${bookings.startAt}<${endAt}`,sql`${bookings.endAt}>${startAt}`)).limit(1),tx.select({id:blockedSlots.id}).from(blockedSlots).where(and(eq(blockedSlots.companyId,company.id),eq(blockedSlots.courtId,courtId),sql`${blockedSlots.startAt}<${endAt}`,sql`${blockedSlots.endAt}>${startAt}`)).limit(1)]);if(conflict.length||block.length)throw fail(409,'Este horário acabou de ficar indisponível. Escolha outro.');if(await findMonthlyConflict(tx,company.id,courtId,startAt,endAt))throw fail(409,'Este horário acabou de ficar indisponível. Escolha outro.');const client=(await tx.select().from(clients).where(and(eq(clients.companyId,company.id),eq(clients.phone,phone))).limit(1))[0],clientId=client?.id||randomUUID(),now=new Date().toISOString();if(client)await tx.update(clients).set(email?{name,email}:{name}).where(eq(clients.id,clientId));else await tx.insert(clients).values({id:clientId,companyId:company.id,name,phone,email:email||null,createdAt:now});const tariffs=await tx.select({weekday:companyPriceSlots.weekday,startTime:companyPriceSlots.startTime,endTime:companyPriceSlots.endTime,priceCents:companyPriceSlots.priceCents}).from(companyPriceSlots).where(eq(companyPriceSlots.companyId,company.id));const amount=bookingAmountCents(startAt,endAt,court.priceCents,tariffs),id=randomUUID();await tx.insert(bookings).values({id,companyId:company.id,courtId,clientId,customerName:name,customerPhone:phone,startAt,endAt,amountCents:amount,status:'pending',source:'public',cancelReason:'',createdAt:now,updatedAt:now});return {id,status:'pending',start_at:startAt,end_at:endAt,amount_cents:amount};});/* Pagamento antecipado: Pix gerado na hora (vale PIX_MINUTES e segura o horário). Se o Pix falhar, a reserva é desfeita para não travar o horário. */
  if(!policy||result.amount_cents<1)return reply.code(201).send({booking:result,payment:null});
  try{
   const charge=await createBookingPixCharge(company.id,result.id,email),token=await attachPixStatusToken(company.id,result.id);
   return reply.code(201).send({booking:result,payment:{qr_code:charge.qrCode,qr_base64:charge.qrBase64,amount_cents:charge.amountCents,total_amount_cents:charge.totalAmountCents||result.amount_cents,expires_at:charge.expiresAt||null,token}});
  }catch(error){
   req.log.warn({err:error,bookingId:result.id},'public_pix_failed');
   await db.transaction(tx=>changeBookingStatus(tx,{companyId:company.id,userId:null,bookingId:result.id,status:'cancelled',reason:'Pix não gerado na página pública',source:'public'}));
   return reply.code(502).send({error:{code:'PIX_UNAVAILABLE',message:'Não foi possível gerar o Pix agora. Tente de novo em instantes.',requestId:req.id}});
  }
 });
 // Semana na página pública: quais dias têm algum horário livre (só leitura).
 app.get('/api/public/arenas/:slug/days',async req=>{
  const {slug}=req.params as {slug:string},q=req.query as {from?:string},from=String(q.from||dayToday());if(!/^\d{4}-\d{2}-\d{2}$/.test(from))throw fail(400,'Data inválida.');
  const company=(await db.select({id:companies.id}).from(companies).where(and(eq(companies.slug,slug),eq(companies.status,'active'))).limit(1))[0];if(!company)throw fail(404,'Arena não encontrada.');
  const dates=Array.from({length:7},(_,i)=>{const d=new Date(`${from}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+i);return d.toISOString().slice(0,10);}),last=dates.at(-1)!;
  const [cs,bs,blocked,members,hours]=await Promise.all([db.select({id:courts.id}).from(courts).where(and(eq(courts.companyId,company.id),eq(courts.active,true))),db.select({court:bookings.courtId,start:bookings.startAt,end:bookings.endAt}).from(bookings).where(and(eq(bookings.companyId,company.id),ne(bookings.status,'cancelled'),gte(bookings.startAt,`${from}T00:00:00.000Z`),lt(bookings.startAt,`${last}T24:00:00.000Z`))),db.select({court:blockedSlots.courtId,start:blockedSlots.startAt,end:blockedSlots.endAt}).from(blockedSlots).where(and(eq(blockedSlots.companyId,company.id),gte(blockedSlots.startAt,`${from}T00:00:00.000Z`),lt(blockedSlots.startAt,`${last}T24:00:00.000Z`))),db.select().from(monthlyMembers).where(and(eq(monthlyMembers.companyId,company.id),eq(monthlyMembers.status,'active'))),db.select().from(companyHours).where(eq(companyHours.companyId,company.id))]);
  const today=dayToday(),now=toMinutes(nowTime()),limit=new Date(`${today}T12:00:00Z`);limit.setUTCDate(limit.getUTCDate()+90);const lastDay=limit.toISOString().slice(0,10);
  return {days:dates.map(date=>{
   const weekday=new Date(`${date}T12:00:00Z`).getUTCDay(),hour=hours.find(h=>h.weekday===weekday);
   if(date<today||date>lastDay||!hour?.isOpen)return {date,open:Boolean(hour?.isOpen),has_free:false};
   const open=toMinutes(hour.openTime),close=toMinutes(hour.closeTime),notBefore=date===today?now+1:0;
   const hasFree=cs.some(c=>{const busy:Busy[]=[...bs,...blocked].filter(x=>x.court===c.id&&x.start.slice(0,10)===date).map(x=>({start:toMinutes(x.start.slice(11,16)),end:toMinutes(x.end.slice(11,16))}));for(const m of members)if(m.courtId===c.id&&m.weekday===weekday){const s0=toMinutes(m.startTime);busy.push({start:s0,end:s0+m.durationMinutes});}return freeStarts(open,close,notBefore,busy).length>0;});
   return {date,open:true,has_free:hasFree};
  })};
 });
 // Situação do Pix para a tela de pagamento (precisa do código entregue na reserva). Contador próprio de requisições.
 app.get('/api/public/arenas/:slug/bookings/:id/payment',{config:{rateLimit:{max:120,timeWindow:60000}}},async req=>{
  const {slug,id}=req.params as {slug:string;id:string},token=String((req.query as {token?:string}).token||'');
  const company=(await db.select({id:companies.id}).from(companies).where(and(eq(companies.slug,slug),eq(companies.status,'active'))).limit(1))[0];if(!company)throw fail(404,'Arena não encontrada.');
  const status=await publicPixStatus(company.id,id,token);if(!status)throw fail(404,'Pagamento não encontrado.');return status;
 });
 app.get('/api/public/reviews/:token',async req=>{const {token}=req.params as {token:string};if(!/^[A-Za-z0-9_-]{30,80}$/.test(token))throw fail(404,'Este link de avaliação expirou ou não existe.');const row=(await db.select({link:reviewLinks,booking:bookings,company:companies}).from(reviewLinks).innerJoin(bookings,eq(reviewLinks.bookingId,bookings.id)).innerJoin(companies,eq(reviewLinks.companyId,companies.id)).where(and(eq(reviewLinks.tokenHash,hash(token)),sql`${reviewLinks.expiresAt}>${new Date().toISOString()}`)).limit(1))[0];if(!row)throw fail(404,'Este link de avaliação expirou ou não existe.');return {arena:row.company.name,customer:row.booking.customerName,date:row.booking.startAt.slice(0,10),submitted:Boolean(row.link.submittedAt)};});
 app.post('/api/public/reviews/:token',{config:{rateLimit:{max:10,timeWindow:10*60*1000}}},async(req,reply)=>{const {token}=req.params as {token:string},row=(await db.select({link:reviewLinks,booking:bookings}).from(reviewLinks).innerJoin(bookings,eq(reviewLinks.bookingId,bookings.id)).where(and(eq(reviewLinks.tokenHash,hash(token)),sql`${reviewLinks.expiresAt}>${new Date().toISOString()}`)).limit(1))[0];if(!row)throw fail(404,'Este link de avaliação expirou ou não existe.');if(row.link.submittedAt)throw fail(409,'Esta avaliação já foi enviada.');const b=bodyOf(req),rating=Number(b.rating),comment=String(b.comment||'').trim().slice(0,1000);if(!Number.isInteger(rating)||rating<1||rating>5)throw fail(400,'Escolha uma nota de 1 a 5.');const now=new Date().toISOString();await db.transaction(async tx=>{await tx.insert(reviews).values({id:randomUUID(),companyId:row.link.companyId,bookingId:row.booking.id,customerName:row.booking.customerName,rating,comment,createdAt:now});const updated=await tx.update(reviewLinks).set({submittedAt:now}).where(and(eq(reviewLinks.id,row.link.id),sql`${reviewLinks.submittedAt} IS NULL`)).returning({id:reviewLinks.id});if(!updated.length)throw fail(409,'Esta avaliação já foi enviada.');});return reply.code(201).send({ok:true});});
 app.get('/api/reviews',{preHandler:app.authenticate},async req=>{const user=(req as typeof req & {user:{company:{id:string}|null}}).user;if(!user?.company)throw fail(403,'Esta conta não pertence a uma arena.');const list=await db.select().from(reviews).where(eq(reviews.companyId,user.company.id)).orderBy(sql`${reviews.createdAt} DESC`).limit(100);const avg=list.length?Math.round(list.reduce((n,x)=>n+x.rating,0)/list.length*10)/10:0;return {reviews:list.map(x=>({...x,customer_name:x.customerName,created_at:x.createdAt})),average:{average:avg,count:list.length}};});
}
