import { randomUUID } from 'node:crypto';
import { and, asc, eq, sql } from 'drizzle-orm';
import type { FastifyInstance } from 'fastify';
import { companies, financeEntries, tournamentEntries, tournamentMatches, tournaments } from '@quadrasflow/database';
import { db } from './database.js';
import { isUniqueViolation } from './db-errors.js';
import { adminOf, audit, companyOf, fail, text } from './arena.js';
const auth=(app:FastifyInstance)=>({preHandler:app.authenticate});const bodyOf=(req:{body?:unknown})=>(req.body||{}) as Record<string,unknown>;
export async function registerTournamentRoutes(app:FastifyInstance){const protectedRoute=auth(app);
 app.get('/api/tournaments',protectedRoute,async req=>{const companyId=companyOf(req);const [t, e, m]=await Promise.all([db.select().from(tournaments).where(eq(tournaments.companyId,companyId)).orderBy(asc(tournaments.startDate)),db.select({entry:tournamentEntries,tournamentName:tournaments.name,entryFeeCents:tournaments.entryFeeCents}).from(tournamentEntries).innerJoin(tournaments,eq(tournamentEntries.tournamentId,tournaments.id)).where(eq(tournaments.companyId,companyId)),db.select({match:tournamentMatches,tournamentName:tournaments.name}).from(tournamentMatches).innerJoin(tournaments,eq(tournamentMatches.tournamentId,tournaments.id)).where(eq(tournaments.companyId,companyId)).orderBy(asc(tournaments.startDate),asc(tournamentMatches.round),asc(tournamentMatches.slot))]);return {tournaments:await Promise.all(t.map(async x=>({...x,entries_count:(await db.select({id:tournamentEntries.id}).from(tournamentEntries).where(eq(tournamentEntries.tournamentId,x.id))).length,start_date:x.startDate,entry_fee_cents:x.entryFeeCents,created_at:x.createdAt}))),entries:e.map(({entry:x,tournamentName,entryFeeCents})=>({...x,tournament_id:x.tournamentId,tournament_name:tournamentName,entry_fee_cents:entryFeeCents,player_name:x.playerName,paid:x.paid?1:0,created_at:x.createdAt})),matches:m.map(({match:x,tournamentName})=>({...x,tournament_id:x.tournamentId,tournament_name:tournamentName,player_a:x.playerA,player_b:x.playerB,score_a:x.scoreA,score_b:x.scoreB}))};});
 app.post('/api/tournaments',protectedRoute,async(req,reply)=>{const user=adminOf(req),companyId=companyOf(req),b=bodyOf(req),name=text(b.name,'o nome do torneio'),sport=text(b.sport,'a modalidade'),category=String(b.category||'').trim().slice(0,80),startDate=String(b.startDate||''),entryFeeCents=Math.round(Number(b.entryFeeCents||0)),capacity=Math.trunc(Number(b.capacity||0));if(!/^\d{4}-\d{2}-\d{2}$/.test(startDate)||Number.isNaN(Date.parse(`${startDate}T00:00:00Z`))||!Number.isInteger(entryFeeCents)||entryFeeCents<0||entryFeeCents>100000000||!Number.isInteger(capacity)||capacity<2||capacity>512)throw fail(400,'Confira a data, taxa e capacidade.');const id=randomUUID(),createdAt=new Date().toISOString();await db.insert(tournaments).values({id,companyId,name,sport,category,startDate,entryFeeCents,capacity,status:'open',createdAt});await audit(companyId,user.id,'tournament.created','tournament',id);return reply.code(201).send({id});});
 app.patch('/api/tournaments/:id/status',protectedRoute,async req=>{const user=adminOf(req),companyId=companyOf(req),{id}=req.params as {id:string},status=String(bodyOf(req).status||'');if(!['open','in_progress','finished','cancelled'].includes(status))throw fail(400,'Status inválido.');const result=await db.update(tournaments).set({status}).where(and(eq(tournaments.id,id),eq(tournaments.companyId,companyId))).returning({id:tournaments.id});if(!result.length)throw fail(404,'Torneio não encontrado.');await audit(companyId,user.id,`tournament.${status}`,'tournament',id);return {ok:true};});
 app.post('/api/tournaments/:id/bracket',protectedRoute,async(req,reply)=>{const user=adminOf(req),companyId=companyOf(req),{id}=req.params as {id:string},t=(await db.select().from(tournaments).where(and(eq(tournaments.id,id),eq(tournaments.companyId,companyId))).limit(1))[0];if(!t)throw fail(404,'Torneio não encontrado.');const entrants=await db.select().from(tournamentEntries).where(eq(tournamentEntries.tournamentId,id));const eligible=entrants.filter(e=>t.entryFeeCents===0||e.paid).map(e=>e.playerName);if(eligible.length<2)throw fail(400,'Confirme pelo menos duas inscrições antes de gerar a chave.');if((await db.select({id:tournamentMatches.id}).from(tournamentMatches).where(eq(tournamentMatches.tournamentId,id)).limit(1)).length)throw fail(409,'A chave já foi gerada.');const players=[...eligible];for(let i=players.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[players[i],players[j]]=[players[j]!,players[i]!];}const size=2**Math.ceil(Math.log2(players.length)),rounds=Math.log2(size),rows:typeof tournamentMatches.$inferInsert[]=[];for(let slot=0;slot<size/2;slot++)rows.push({id:randomUUID(),tournamentId:id,round:1,slot:slot+1,playerA:players[slot*2]||null,playerB:players[slot*2+1]||null,scoreA:null,scoreB:null,winner:null});for(let round=2;round<=rounds;round++)for(let slot=1;slot<=size/(2**round);slot++)rows.push({id:randomUUID(),tournamentId:id,round,slot,playerA:null,playerB:null,scoreA:null,scoreB:null,winner:null});for(const row of rows.filter(x=>x.round===1)){const winner=row.playerA||row.playerB;if(winner&&(!row.playerA||!row.playerB)){row.winner=winner;const next=rows.find(x=>x.round===2&&x.slot===Math.ceil(row.slot!/2));if(next){if(row.slot!%2)next.playerA=winner;else next.playerB=winner;}}}await db.transaction(async tx=>{await tx.insert(tournamentMatches).values(rows);await tx.update(tournaments).set({status:'in_progress'}).where(eq(tournaments.id,id));});await audit(companyId,user.id,'tournament.bracket_generated','tournament',id,{players:eligible.length});return reply.code(201).send({matches:rows});});
 app.patch('/api/tournaments/entries',protectedRoute,async req=>{const user=adminOf(req),companyId=companyOf(req),b=bodyOf(req),entryId=String(b.entryId||''),entry=(await db.select({entry:tournamentEntries,tournament:tournaments}).from(tournamentEntries).innerJoin(tournaments,eq(tournamentEntries.tournamentId,tournaments.id)).where(and(eq(tournamentEntries.id,entryId),eq(tournaments.companyId,companyId))).limit(1))[0];if(!entry)throw fail(404,'Inscrição não encontrada.');const paid=Boolean(b.paid),now=new Date().toISOString();await db.transaction(async tx=>{await tx.update(tournamentEntries).set({paid}).where(eq(tournamentEntries.id,entryId));if(paid&&entry.tournament.entryFeeCents>0){const prior=await tx.select({id:financeEntries.id}).from(financeEntries).where(eq(financeEntries.tournamentEntryId,entryId)).limit(1);if(!prior.length)await tx.insert(financeEntries).values({id:randomUUID(),companyId,bookingId:null,monthlyChargeId:null,tournamentEntryId:entryId,kind:'income',category:'Torneios',description:entry.tournament.name,amountCents:entry.tournament.entryFeeCents,dueDate:new Date().toISOString().slice(0,10),paidAt:now,createdAt:now});}else await tx.delete(financeEntries).where(and(eq(financeEntries.tournamentEntryId,entryId),eq(financeEntries.companyId,companyId)));});await audit(companyId,user.id,'tournament.entry_payment_updated','tournament_entry',entryId,{paid});return {ok:true};});
 app.patch('/api/tournament-matches/:id',protectedRoute,async req=>{
   const user=adminOf(req), companyId=companyOf(req), {id}=req.params as {id:string}, b=bodyOf(req);
   const row=(await db.select({match:tournamentMatches,tournament:tournaments}).from(tournamentMatches).innerJoin(tournaments,eq(tournamentMatches.tournamentId,tournaments.id)).where(and(eq(tournamentMatches.id,id),eq(tournaments.companyId,companyId))).limit(1))[0];
   const scoreA=Number(b.scoreA), scoreB=Number(b.scoreB);
   if(!row)throw fail(404,'Partida não encontrada.'); const m=row.match;
   if(m.winner)throw fail(409,'Esta partida já tem resultado.');
   if(!m.playerA||!m.playerB||!Number.isInteger(scoreA)||!Number.isInteger(scoreB)||scoreA<0||scoreB<0||scoreA===scoreB)throw fail(400,'Informe um placar válido para dois participantes.');
   const winner=scoreA>scoreB?m.playerA:m.playerB;
   await db.transaction(async tx=>{
     await tx.update(tournamentMatches).set({scoreA,scoreB,winner}).where(eq(tournamentMatches.id,id));
     const next=(await tx.select().from(tournamentMatches).where(and(eq(tournamentMatches.tournamentId,m.tournamentId),eq(tournamentMatches.round,m.round+1),eq(tournamentMatches.slot,Math.ceil(m.slot/2)))).limit(1))[0];
     if(next)await tx.update(tournamentMatches).set(m.slot%2?{playerA:winner}:{playerB:winner}).where(eq(tournamentMatches.id,next.id));
     else await tx.update(tournaments).set({status:'finished'}).where(eq(tournaments.id,m.tournamentId));
   });
   await audit(companyId,user.id,'tournament.match_scored','tournament_match',id,{scoreA,scoreB}); return {ok:true,winner};
 });
 app.get('/api/public/arenas/:slug/tournaments',async req=>{const {slug}=req.params as {slug:string};const company=(await db.select().from(companies).where(and(eq(companies.slug,slug),eq(companies.status,'active'))).limit(1))[0];if(!company)throw fail(404,'Arena não encontrada.');const rows=await db.select().from(tournaments).where(and(eq(tournaments.companyId,company.id),eq(tournaments.status,'open'))).orderBy(asc(tournaments.startDate));return {tournaments:await Promise.all(rows.map(async t=>({id:t.id,name:t.name,sport:t.sport,category:t.category,start_date:t.startDate,entry_fee_cents:t.entryFeeCents,capacity:t.capacity,entries_count:(await db.select({id:tournamentEntries.id}).from(tournamentEntries).where(eq(tournamentEntries.tournamentId,t.id))).length})))};});
 app.post('/api/public/tournaments/:id/entries',{config:{rateLimit:{max:10,timeWindow:10*60*1000}}},async(req,reply)=>{const {id}=req.params as {id:string},t=(await db.select().from(tournaments).where(and(eq(tournaments.id,id),eq(tournaments.status,'open'))).limit(1))[0];if(!t)throw fail(404,'Inscrições não estão abertas.');const b=bodyOf(req),name=text(b.name,'seu nome'),phone=digits(b.phone);if(phone.length<10||phone.length>15)throw fail(400,'Informe WhatsApp válido.');const result=await db.transaction(async tx=>{const count=await tx.select({value:sql<number>`count(*)::int`}).from(tournamentEntries).where(eq(tournamentEntries.tournamentId,id));if(Number(count[0]?.value||0)>=t.capacity)throw fail(409,'As vagas desse torneio acabaram.');const eid=randomUUID();try{await tx.insert(tournamentEntries).values({id:eid,tournamentId:id,playerName:name,phone,paid:false,createdAt:new Date().toISOString()});}catch(e){if(isUniqueViolation(e))throw fail(409,'Este WhatsApp já está inscrito.');throw e;}return eid;});return reply.code(201).send({id:result,payment_required:t.entryFeeCents>0,entry_fee_cents:t.entryFeeCents});});
}
function digits(value:unknown){return String(value??'').replace(/\D/g,'');}
