import { boolean, index, integer, jsonb, pgTable, primaryKey, text, uniqueIndex } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';

const created = () => text('created_at').notNull();
export const companies = pgTable('companies', {
  id: text('id').primaryKey(), name: text('name').notNull(), slug: text('slug').notNull().unique(), description: text('description').notNull().default(''),
  address: text('address').notNull().default(''), addressNumber: text('address_number').notNull().default(''), district: text('district').notNull().default(''), zipCode: text('zip_code').notNull().default(''),
  phone: text('phone').notNull().default(''), city: text('city').notNull().default(''), state: text('state').notNull().default(''), amenities: jsonb('amenities').$type<string[]>().notNull().default([]), photos: jsonb('photos').$type<string[]>().notNull().default([]), publicOptions: jsonb('public_options').$type<Record<string, unknown>>().notNull().default({}), logoUrl: text('logo_url').notNull().default(''),
  cancellationHours: integer('cancellation_hours').notNull().default(24), cancellationFeePercent: integer('cancellation_fee_percent').notNull().default(0), onboardingCompleted: boolean('onboarding_completed').notNull().default(false), status: text('status').notNull().default('active'), createdAt: created(),
});
export const users = pgTable('users', {
  id: text('id').primaryKey(), companyId: text('company_id').references(() => companies.id, { onDelete: 'cascade' }), name: text('name').notNull(), email: text('email').notNull(), passwordHash: text('password_hash').notNull(), passwordSalt: text('password_salt').notNull(), role: text('role').notNull(), active: boolean('active').notNull().default(true), createdAt: created(), lastLoginAt: text('last_login_at'),
}, (t) => [index('users_company_idx').on(t.companyId), uniqueIndex('users_email_lower_idx').on(sql`lower(${t.email})`)]);
// Convite de acesso à equipe: guarda só o hash do token do link (uso único, com validade).
export const userInvites = pgTable('user_invites', { id: text('id').primaryKey(), companyId: text('company_id').notNull().references(() => companies.id, { onDelete: 'cascade' }), name: text('name').notNull(), email: text('email').notNull(), role: text('role').notNull().default('staff'), tokenHash: text('token_hash').notNull().unique(), expiresAt: text('expires_at').notNull(), acceptedAt: text('accepted_at'), revokedAt: text('revoked_at'), createdBy: text('created_by').references(() => users.id, { onDelete: 'set null' }), createdAt: created() }, (t) => [index('user_invites_company_idx').on(t.companyId), index('user_invites_email_idx').on(sql`lower(${t.email})`)]);
export const sessions = pgTable('sessions', { tokenHash: text('token_hash').primaryKey(), userId: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }), expiresAt: text('expires_at').notNull(), createdAt: created() }, (t) => [index('sessions_expiry_idx').on(t.expiresAt)]);
export const companyHours = pgTable('company_hours', { companyId: text('company_id').notNull().references(() => companies.id, { onDelete: 'cascade' }), weekday: integer('weekday').notNull(), isOpen: boolean('is_open').notNull().default(true), openTime: text('open_time').notNull().default('08:00'), closeTime: text('close_time').notNull().default('23:00') }, (t) => [primaryKey({ columns: [t.companyId, t.weekday] })]);
export const companyPriceSlots = pgTable('company_price_slots', { companyId: text('company_id').notNull().references(() => companies.id, { onDelete: 'cascade' }), weekday: integer('weekday').notNull(), band: text('band').notNull(), startTime: text('start_time').notNull(), endTime: text('end_time').notNull(), priceCents: integer('price_cents').notNull() }, (t) => [primaryKey({ columns: [t.companyId, t.weekday, t.band] })]);
export const courts = pgTable('courts', { id: text('id').primaryKey(), companyId: text('company_id').notNull().references(() => companies.id, { onDelete: 'cascade' }), name: text('name').notNull(), sport: text('sport').notNull(), priceCents: integer('price_cents').notNull().default(0), surface: text('surface').notNull().default(''), covering: text('covering').notNull().default(''), players: integer('players').notNull().default(0), sports: jsonb('sports').$type<string[]>().notNull().default([]), photoUrl: text('photo_url'), photos: jsonb('photos').$type<string[]>().notNull().default([]), active: boolean('active').notNull().default(true), bookingRules: jsonb('booking_rules').$type<Record<string, unknown>>().notNull().default({}), createdAt: created() }, (t) => [uniqueIndex('courts_company_name_idx').on(t.companyId, t.name)]);
export const clients = pgTable('clients', { id: text('id').primaryKey(), companyId: text('company_id').notNull().references(() => companies.id, { onDelete: 'cascade' }), name: text('name').notNull(), phone: text('phone'), email: text('email'), notes: text('notes').notNull().default(''), createdAt: created() }, (t) => [index('clients_company_idx').on(t.companyId, t.name)]);
export const bookings = pgTable('bookings', { id: text('id').primaryKey(), companyId: text('company_id').notNull().references(() => companies.id, { onDelete: 'cascade' }), courtId: text('court_id').notNull().references(() => courts.id, { onDelete: 'cascade' }), clientId: text('client_id').references(() => clients.id, { onDelete: 'set null' }), customerName: text('customer_name').notNull(), customerPhone: text('customer_phone'), startAt: text('start_at').notNull(), endAt: text('end_at').notNull(), amountCents: integer('amount_cents').notNull().default(0), status: text('status').notNull().default('pending'), source: text('source').notNull().default('staff'), cancelReason: text('cancel_reason').notNull().default(''), createdAt: created(), updatedAt: text('updated_at').notNull().default('') }, (t) => [index('bookings_company_date_idx').on(t.companyId, t.startAt, t.endAt), index('bookings_court_date_idx').on(t.courtId, t.startAt, t.endAt), index('bookings_client_idx').on(t.clientId)]);
export const blockedSlots = pgTable('blocked_slots', { id: text('id').primaryKey(), companyId: text('company_id').notNull().references(() => companies.id, { onDelete: 'cascade' }), courtId: text('court_id').notNull().references(() => courts.id, { onDelete: 'cascade' }), reason: text('reason').notNull(), startAt: text('start_at').notNull(), endAt: text('end_at').notNull(), createdAt: created() }, (t) => [index('blocks_court_date_idx').on(t.courtId, t.startAt, t.endAt)]);
export const bookingEvents = pgTable('booking_events', { id: text('id').primaryKey(), companyId: text('company_id').notNull().references(() => companies.id, { onDelete: 'cascade' }), bookingId: text('booking_id').notNull().references(() => bookings.id, { onDelete: 'cascade' }), userId: text('user_id').references(() => users.id, { onDelete: 'set null' }), event: text('event').notNull(), details: jsonb('details').notNull().default({}), createdAt: created() });
export const monthlyMembers = pgTable('monthly_members', { id: text('id').primaryKey(), companyId: text('company_id').notNull().references(() => companies.id, { onDelete: 'cascade' }), clientId: text('client_id').notNull().references(() => clients.id, { onDelete: 'cascade' }), courtId: text('court_id').notNull().references(() => courts.id, { onDelete: 'cascade' }), weekday: integer('weekday').notNull(), startTime: text('start_time').notNull(), durationMinutes: integer('duration_minutes').notNull(), amountCents: integer('amount_cents').notNull(), status: text('status').notNull().default('active'), createdAt: created() });
export const monthlyCharges = pgTable('monthly_charges', { id: text('id').primaryKey(), companyId: text('company_id').notNull().references(() => companies.id, { onDelete: 'cascade' }), memberId: text('member_id').notNull().references(() => monthlyMembers.id, { onDelete: 'cascade' }), cycle: text('cycle').notNull(), amountCents: integer('amount_cents').notNull(), dueDate: text('due_date').notNull(), paidAt: text('paid_at'), createdAt: created() }, (t) => [uniqueIndex('monthly_charge_cycle_idx').on(t.memberId, t.cycle)]);
export const tournaments = pgTable('tournaments', { id: text('id').primaryKey(), companyId: text('company_id').notNull().references(() => companies.id, { onDelete: 'cascade' }), name: text('name').notNull(), sport: text('sport').notNull(), category: text('category').notNull().default(''), startDate: text('start_date').notNull(), entryFeeCents: integer('entry_fee_cents').notNull().default(0), capacity: integer('capacity').notNull().default(0), status: text('status').notNull().default('open'), createdAt: created() });
export const tournamentEntries = pgTable('tournament_entries', { id: text('id').primaryKey(), tournamentId: text('tournament_id').notNull().references(() => tournaments.id, { onDelete: 'cascade' }), playerName: text('player_name').notNull(), phone: text('phone').notNull(), paid: boolean('paid').notNull().default(false), createdAt: created() }, (t) => [uniqueIndex('tournament_entry_phone_idx').on(t.tournamentId, t.phone)]);
export const tournamentMatches = pgTable('tournament_matches', { id: text('id').primaryKey(), tournamentId: text('tournament_id').notNull().references(() => tournaments.id, { onDelete: 'cascade' }), round: integer('round').notNull(), slot: integer('slot').notNull(), playerA: text('player_a'), playerB: text('player_b'), scoreA: integer('score_a'), scoreB: integer('score_b'), winner: text('winner') }, (t) => [uniqueIndex('tournament_match_slot_idx').on(t.tournamentId, t.round, t.slot)]);
export const financeEntries = pgTable('finance_entries', { id: text('id').primaryKey(), companyId: text('company_id').notNull().references(() => companies.id, { onDelete: 'cascade' }), bookingId: text('booking_id').references(() => bookings.id, { onDelete: 'set null' }), monthlyChargeId: text('monthly_charge_id').references(() => monthlyCharges.id, { onDelete: 'set null' }), tournamentEntryId: text('tournament_entry_id').references(() => tournamentEntries.id, { onDelete: 'set null' }), kind: text('kind').notNull(), category: text('category').notNull(), description: text('description').notNull(), amountCents: integer('amount_cents').notNull(), dueDate: text('due_date').notNull(), paidAt: text('paid_at'), createdAt: created() }, (t) => [index('finance_company_due_idx').on(t.companyId, t.dueDate), uniqueIndex('finance_booking_open_once_idx').on(t.bookingId).where(sql`${t.bookingId} IS NOT NULL AND ${t.paidAt} IS NULL`), uniqueIndex('finance_monthly_charge_once_idx').on(t.monthlyChargeId).where(sql`${t.monthlyChargeId} IS NOT NULL`), uniqueIndex('finance_tournament_entry_once_idx').on(t.tournamentEntryId).where(sql`${t.tournamentEntryId} IS NOT NULL`)]);
export const reviews = pgTable('reviews', { id: text('id').primaryKey(), companyId: text('company_id').notNull().references(() => companies.id, { onDelete: 'cascade' }), bookingId: text('booking_id').references(() => bookings.id, { onDelete: 'set null' }), customerName: text('customer_name').notNull(), rating: integer('rating').notNull(), comment: text('comment').notNull().default(''), createdAt: created() }, (t) => [uniqueIndex('reviews_booking_once_idx').on(t.bookingId).where(sql`${t.bookingId} IS NOT NULL`)]);
export const reviewLinks = pgTable('review_links', { id: text('id').primaryKey(), companyId: text('company_id').notNull().references(() => companies.id, { onDelete: 'cascade' }), bookingId: text('booking_id').notNull().references(() => bookings.id, { onDelete: 'cascade' }), tokenHash: text('token_hash').notNull().unique(), expiresAt: text('expires_at').notNull(), submittedAt: text('submitted_at'), createdAt: created() }, (t) => [uniqueIndex('review_links_booking_once_idx').on(t.bookingId)]);
export const integrationSettings = pgTable('integration_settings', { companyId: text('company_id').notNull().references(() => companies.id, { onDelete: 'cascade' }), provider: text('provider').notNull(), settings: jsonb('settings').notNull().default({}), updatedAt: text('updated_at').notNull() }, (t) => [primaryKey({ columns: [t.companyId, t.provider] })]);
export const webhookEvents = pgTable('webhook_events', { provider: text('provider').notNull(), eventId: text('event_id').notNull(), companyId: text('company_id').references(() => companies.id, { onDelete: 'cascade' }), receivedAt: text('received_at').notNull() }, (t) => [primaryKey({ columns: [t.provider, t.eventId] })]);
export const whatsappConversations = pgTable('whatsapp_conversations', { companyId: text('company_id').notNull().references(() => companies.id, { onDelete: 'cascade' }), phone: text('phone').notNull(), step: text('step').notNull().default(''), context: jsonb('context').notNull().default({}), updatedAt: text('updated_at').notNull() }, (t) => [primaryKey({ columns: [t.companyId, t.phone] })]);
export const whatsappMessages = pgTable('whatsapp_messages', { id: text('id').primaryKey(), companyId: text('company_id').notNull().references(() => companies.id, { onDelete: 'cascade' }), eventId: text('event_id').notNull(), phone: text('phone').notNull(), direction: text('direction').notNull(), body: text('body').notNull(), createdAt: created() }, (t) => [uniqueIndex('whatsapp_msg_event_direction_idx').on(t.companyId, t.eventId, t.direction)]);
export const messageTemplates = pgTable('message_templates', { id: text('id').primaryKey(), companyId: text('company_id').notNull().references(() => companies.id, { onDelete: 'cascade' }), title: text('title').notNull(), category: text('category').notNull(), body: text('body').notNull(), active: boolean('active').notNull().default(true), createdAt: created() });
export const appAudit = pgTable('app_audit', { id: text('id').primaryKey(), companyId: text('company_id').references(() => companies.id, { onDelete: 'cascade' }), userId: text('user_id').references(() => users.id, { onDelete: 'set null' }), action: text('action').notNull(), entity: text('entity').notNull(), entityId: text('entity_id'), details: jsonb('details').notNull().default({}), createdAt: created() });

export const whatsappDeliveries = pgTable('whatsapp_deliveries', {
 id:text('id').primaryKey(), companyId:text('company_id').notNull().references(()=>companies.id,{onDelete:'cascade'}),
 bookingId:text('booking_id').references(()=>bookings.id,{onDelete:'cascade'}), kind:text('kind').notNull(),
 destination:text('destination').notNull(), payload:jsonb('payload').$type<Record<string,unknown>>().notNull().default({}),
 status:text('status').notNull().default('pending'), attempts:integer('attempts').notNull().default(0),
 dueAt:text('due_at').notNull(), createdAt:created(), updatedAt:text('updated_at').notNull(), error:text('error').notNull().default(''),
},t=>[index('whatsapp_deliveries_due_idx').on(t.status,t.dueAt)]);
