import { useEffect, useState } from 'react';
import { LoaderCircle, Save } from 'lucide-react';
import { useAuth } from '@/auth/AuthProvider';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { api } from '@/lib/api';
import { ArenaImagePicker } from '@/components/ArenaImagePicker';
import { BrazilStateInput } from '@/components/BrazilStateInput';
import { errorMessage } from '@/lib/format';
type Hour={weekday:number;is_open:boolean|number;open_time:string;close_time:string};
type PriceDay={weekday:number;morning:number;afternoon:number;evening:number};
type Profile={description:string;address:string;city:string;state:string;amenities:string[];photos:string[]};
type MpStatus={connected:boolean;configured:boolean};
const days=['Domingo','Segunda-feira','Terça-feira','Quarta-feira','Quinta-feira','Sexta-feira','Sábado'];
const times=Array.from({length:36},(_,i)=>`${String(6+Math.floor(i/2)).padStart(2,'0')}:${i%2?'30':'00'}`);

export function SettingsPage(){
  const {user}=useAuth();
  const [hours,setHours]=useState<Hour[]>([]);
  const [prices,setPrices]=useState<PriceDay[]>([]);
  const [profile,setProfile]=useState<Profile>({description:'',address:'',city:'',state:'',amenities:[],photos:[]});
  const [mp,setMp]=useState<MpStatus>({connected:false,configured:false});
  const [loading,setLoading]=useState(true),[connecting,setConnecting]=useState(false),[savingHours,setSavingHours]=useState(false),[savingPrices,setSavingPrices]=useState(false),[savingProfile,setSavingProfile]=useState(false),[uploadingPhotos,setUploadingPhotos]=useState(false);
  const [message,setMessage]=useState(''),[error,setError]=useState('');
  const editable=user?.role==='arena_admin';
  useEffect(()=>{Promise.all([api<{weeklyHours:Hour[];prices:PriceDay[];profile:Profile}>('/api/arena/settings'),api<MpStatus>('/api/integrations/mercadopago')]).then(([settings,payment])=>{setHours(settings.weeklyHours.map(h=>({...h,is_open:Boolean(h.is_open)})));setPrices(settings.prices);setProfile({...settings.profile,amenities:settings.profile.amenities||[],photos:settings.profile.photos||[]});setMp(payment)}).catch(e=>setError(errorMessage(e))).finally(()=>setLoading(false))},[]);
  function updateHour(weekday:number,key:keyof Hour,value:unknown){setHours(list=>list.map(h=>h.weekday===weekday?{...h,[key]:value}:h))}
  function updateProfile<K extends keyof Profile>(key:K,value:Profile[K]){setProfile(p=>({...p,[key]:value}))}
  async function saveHours(){setSavingHours(true);setError('');try{await api('/api/arena/settings',{method:'PUT',body:JSON.stringify({weeklyHours:hours.map(h=>({weekday:h.weekday,isOpen:Boolean(h.is_open),openTime:h.open_time,closeTime:h.close_time}))})});setMessage('Horários salvos.')}catch(e){setError(errorMessage(e))}finally{setSavingHours(false)}}
  function updatePrice(weekday:number,key:'morning'|'afternoon'|'evening',value:string){const cents=Math.round(Number(value.replace(',','.'))*100);setPrices(list=>list.map(day=>day.weekday===weekday?{...day,[key]:Number.isFinite(cents)?cents:0}:day))}
  async function savePrices(){setSavingPrices(true);setError('');try{await api('/api/arena/prices',{method:'PUT',body:JSON.stringify({prices})});setMessage('Preços por faixa salvos.')}catch(e){setError(errorMessage(e))}finally{setSavingPrices(false)}}
  async function saveProfile(){setSavingProfile(true);setError('');try{await api('/api/arena/profile',{method:'PUT',body:JSON.stringify({profile})});setMessage('Perfil da arena salvo.')}catch(e){setError(errorMessage(e))}finally{setSavingProfile(false)}}
  async function connectMp(){setConnecting(true);setError('');try{const result=await api<{url:string}>('/api/integrations/mercadopago/connect',{method:'POST',body:'{}'});window.location.assign(result.url)}catch(e){setError(errorMessage(e));setConnecting(false)}}
  const disabled=!editable||loading;
  return <div className="grid gap-5"><header><h1 className="text-2xl font-bold">Configurações</h1><p className="mt-1 text-sm text-muted-foreground">Perfil público, funcionamento e pagamentos.</p></header>
    {error&&<p role="alert" className="rounded-md bg-red-50 p-3 text-sm text-red-700">{error}</p>}{message&&<p role="status" className="rounded-md bg-emerald-50 p-3 text-sm text-emerald-800">{message}</p>}
    {loading?<div className="grid min-h-40 place-items-center"><LoaderCircle className="animate-spin"/></div>:<>
      <Card><CardHeader><CardTitle className="text-base">Mercado Pago · Pix</CardTitle></CardHeader><CardContent className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p className="font-medium">{mp.connected?'Conta Mercado Pago conectada':'Conta vendedora da arena'}</p><p className="text-xs text-muted-foreground">{mp.connected?'As cobranças Pix podem ser geradas nas reservas.':mp.configured?'Conecte a conta do Mercado Pago que receberá os pagamentos.':'As credenciais OAuth ainda não foram configuradas no servidor.'}</p></div><Button className="w-full sm:w-auto" disabled={!editable||!mp.configured||connecting} onClick={()=>void connectMp()}>{connecting&&<LoaderCircle className="animate-spin"/>}{mp.connected?'Reconectar conta':'Conectar Mercado Pago'}</Button></CardContent></Card>
      <Card><CardHeader><CardTitle className="text-base">Horários de funcionamento</CardTitle></CardHeader><CardContent className="grid gap-3">{hours.map(h=><div key={h.weekday} className="grid gap-3 rounded-lg border p-3 sm:grid-cols-[1fr_140px_140px] sm:items-center"><Label className="flex items-center gap-2"><Checkbox disabled={disabled} checked={Boolean(h.is_open)} onCheckedChange={v=>updateHour(h.weekday,'is_open',v===true)}/>{days[h.weekday]}</Label><div className="grid gap-1"><Label className="text-xs text-muted-foreground">Abertura</Label><Select disabled={disabled||!h.is_open} value={h.open_time} onValueChange={v=>updateHour(h.weekday,'open_time',v)}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent>{times.map(t=><SelectItem key={t} value={t}>{t}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-1"><Label className="text-xs text-muted-foreground">Fechamento</Label><Select disabled={disabled||!h.is_open} value={h.close_time} onValueChange={v=>updateHour(h.weekday,'close_time',v)}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent>{times.map(t=><SelectItem key={t} value={t}>{t}</SelectItem>)}</SelectContent></Select></div></div>)}<Button disabled={disabled||savingHours} className="w-full sm:w-fit" onClick={()=>void saveHours()}>{savingHours?<LoaderCircle className="animate-spin"/>:<Save/>}Salvar horários</Button></CardContent></Card>
      <Card><CardHeader><CardTitle className="text-base">Preços por faixa</CardTitle><p className="text-sm text-muted-foreground">Valor por hora para cada dia e horário. O mínimo é R$ 20.</p></CardHeader><CardContent className="grid gap-3"><div className="hidden grid-cols-[minmax(100px,1fr)_repeat(3,minmax(110px,1fr))] gap-2 text-xs font-semibold text-muted-foreground sm:grid"><span>Dia</span><span>08h–12h</span><span>12h–18h</span><span>18h–23h</span></div>{prices.map(day=><div key={day.weekday} className="hidden grid-cols-[minmax(100px,1fr)_repeat(3,minmax(110px,1fr))] items-center gap-2 sm:grid"><Label>{days[day.weekday]}</Label>{(['morning','afternoon','evening'] as const).map((band)=><div key={band} className="relative"><span className="absolute left-2 top-1/2 -translate-y-1/2 text-xs text-muted-foreground">R$</span><Input aria-label={`${days[day.weekday]} ${band==='morning'?'08h–12h':band==='afternoon'?'12h–18h':'18h–23h'}`} disabled={disabled} type="number" min="20" step="0.50" value={(day[band]/100).toFixed(2)} onChange={e=>updatePrice(day.weekday,band,e.target.value)} className="pl-8" /></div>)}</div>)}<div className="grid gap-3 sm:hidden">{prices.map(day=><section key={day.weekday} className="grid gap-3 rounded-lg border p-3"><h3 className="font-semibold">{days[day.weekday]}</h3>{(['morning','afternoon','evening'] as const).map(band=><div key={band} className="grid gap-1"><Label htmlFor={`price-${day.weekday}-${band}`} className="text-xs text-muted-foreground">{band==='morning'?'08h–12h':band==='afternoon'?'12h–18h':'18h–23h'}</Label><div className="relative"><span className="absolute left-2 top-1/2 -translate-y-1/2 text-xs text-muted-foreground">R$</span><Input id={`price-${day.weekday}-${band}`} aria-label={`${days[day.weekday]} ${band}`} disabled={disabled} type="number" min="20" step="0.50" value={(day[band]/100).toFixed(2)} onChange={e=>updatePrice(day.weekday,band,e.target.value)} className="pl-8" /></div></div>)}</section>)}</div><Button disabled={disabled||savingPrices||prices.length!==7} className="w-full sm:w-fit" onClick={()=>void savePrices()}>{savingPrices?<LoaderCircle className="animate-spin"/>:<Save/>}Salvar preços</Button></CardContent></Card>
      <Card><CardHeader><CardTitle className="text-base">Perfil público da arena</CardTitle></CardHeader><CardContent className="grid gap-4"><div className="grid gap-2"><Label htmlFor="profile-description">Descrição</Label><Textarea id="profile-description" maxLength={600} rows={4} disabled={disabled} value={profile.description} onChange={e=>updateProfile('description',e.target.value)}/></div><div className="grid gap-3 sm:grid-cols-2"><div className="grid gap-2"><Label htmlFor="profile-address">Endereço</Label><Input id="profile-address" maxLength={180} disabled={disabled} value={profile.address} onChange={e=>updateProfile('address',e.target.value)}/></div><div className="grid gap-2"><Label htmlFor="profile-city">Cidade</Label><Input id="profile-city" maxLength={100} disabled={disabled} value={profile.city} onChange={e=>updateProfile('city',e.target.value)}/></div></div><div className="grid gap-2 sm:w-64"><Label htmlFor="profile-state">UF</Label><BrazilStateInput id="profile-state" disabled={disabled} value={profile.state} onChange={state=>updateProfile('state',state)}/></div><div className="grid gap-2"><Label>Comodidades (separadas por vírgula)</Label><Input disabled={disabled} value={profile.amenities.join(', ')} onChange={e=>updateProfile('amenities',e.target.value.split(',').map(v=>v.trim()).filter(Boolean))}/></div><ArenaImagePicker label="Fotos da arena" images={profile.photos} maxImages={6} disabled={disabled||savingProfile} onChange={photos=>updateProfile('photos',photos)} onBusyChange={setUploadingPhotos}/><Button disabled={disabled||savingProfile||uploadingPhotos} className="w-full sm:w-fit" onClick={()=>void saveProfile()}>{savingProfile?<LoaderCircle className="animate-spin"/>:<Save/>}Salvar perfil</Button>{!editable&&<p className="text-xs text-muted-foreground">Somente o administrador da arena pode alterar essas informações.</p>}</CardContent></Card>
    </>}
  </div>;
}
