import {WhatsAppServices} from '@/components/WhatsAppServices';
import { useEffect, useState, type FormEvent } from 'react';
import { Bot, Check, Clock3, CreditCard, LoaderCircle, Pencil, Plus, QrCode, Send, Smartphone, Trash2, UserRound } from 'lucide-react';
import { useAuth } from '@/auth/AuthProvider';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { ApiError, api } from '@/lib/api';
import { errorMessage, formatDate } from '@/lib/format';

type Config={session:string;enabled:boolean;status:string;connected:boolean;serviceConfigured:boolean;aiConfigured:boolean;webhookUrl:string};
type BotConfig={paymentMode:'none'|'full'|'percent'|'fixed';paymentPercent:number;paymentFixedCents:number;timeZone:string;enabled:boolean;testMode:boolean;testPhones:string[];welcome:string;handoffMessage:string;reactivateAfterHours:number;humanStart:string;humanEnd:string;outsideHoursMessage:string;notifyPayment:boolean;remindUnpaid:boolean;menuOptions:{id:string;label:string;response:string}[];aiConfigured?:boolean;aiModel?:string};
type Conversation={phone:string;step:string;updated_at:string;last_message:string};type Message={direction:string;body:string;created_at:string};type Template={id:string;title:string;category:string;body:string;active:boolean|number};
const defaultBot:BotConfig={paymentMode:'none',paymentPercent:50,paymentFixedCents:5000,timeZone:'',enabled:true,testMode:false,testPhones:[],welcome:'Como posso te ajudar?\n1 – Agendar horário\n2 – Falar com atendente.',handoffMessage:'Certo! Me conta rapidinho o que você precisa que já encaminho para o responsável. 👇',reactivateAfterHours:4,humanStart:'06:00',humanEnd:'23:00',outsideHoursMessage:'No momento estamos fora do horário de atendimento humano. Você pode agendar pelo nosso app. 😊',notifyPayment:true,remindUnpaid:true,menuOptions:[]};
const flow=[['Menu','text-emerald-600'],['Data','text-blue-600'],['Horário','text-violet-600'],['Duração','text-amber-600'],['Reserva','text-pink-600'],['Pix','text-teal-600']];

export function WhatsAppPage(){
 const {user}=useAuth();const editable=user?.role==='arena_admin';const [tab,setTab]=useState<'config'|'conversas'|'modelos'|'services'>('config');const [config,setConfig]=useState<Config>({session:'',enabled:false,status:'unknown',connected:false,serviceConfigured:false,aiConfigured:false,webhookUrl:''});const [bot,setBot]=useState<BotConfig>(defaultBot);const [status,setStatus]=useState('unknown');const [qr,setQr]=useState('');const [conversations,setConversations]=useState<Conversation[]>([]);const [phone,setPhone]=useState('');const [messages,setMessages]=useState<Message[]>([]);const [reply,setReply]=useState('');const [templates,setTemplates]=useState<Template[]>([]);const [templateDraft,setTemplateDraft]=useState<Template|null>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 async function load(){setLoading(true);const paths=['/api/integrations/waha','/api/integrations/waha/status','/api/whatsapp/conversations','/api/message-templates','/api/whatsapp/bot-settings'] as const;const results=await Promise.allSettled([api<Config>(paths[0]),api<{status:string}>(paths[1]),api<{conversations:Conversation[]}>(paths[2]),api<{templates:Template[]}>(paths[3]),api<BotConfig>(paths[4])]);const labels=['estado da conexão','estado da sessão','conversas','modelos de mensagem','configurações do bot'];const errors:string[]=[];results.forEach((result,index)=>{if(result.status==='rejected')errors.push(`${labels[index]}: ${errorMessage(result.reason)}`)});if(results[0].status==='fulfilled')setConfig(results[0].value);if(results[1].status==='fulfilled')setStatus(results[1].value.status);if(results[2].status==='fulfilled')setConversations(results[2].value.conversations);if(results[3].status==='fulfilled')setTemplates(results[3].value.templates);if(results[4].status==='fulfilled')setBot({...defaultBot,...results[4].value});setError(errors.join(' · '));setLoading(false)}useEffect(()=>{void load()},[]);
 async function selectConversation(value:string){setPhone(value);try{setMessages((await api<{messages:Message[]}>(`/api/whatsapp/conversations?phone=${encodeURIComponent(value)}`)).messages)}catch(e){setError(errorMessage(e))}}
 useEffect(()=>{const contact=new URLSearchParams(window.location.search).get('phone');if(contact&&/^\d{10,15}$/.test(contact)){setTab('conversas');void selectConversation(contact);}},[]);
 async function send(e:FormEvent){e.preventDefault();try{await api('/api/whatsapp/reply',{method:'POST',body:JSON.stringify({phone,message:reply})});setReply('');await selectConversation(phone);await load()}catch(e){setError(errorMessage(e))}}
 async function connectWhatsApp(){setSaving(true);setQr('');setError('');setNotice('Preparando a conexão com o WhatsApp…');try{const saved=await api<{session:string}>('/api/integrations/waha/connect',{method:'POST',body:'{}'});setConfig(current=>({...current,session:saved.session,enabled:true}));for(let attempt=0;attempt<20;attempt++){try{const result=await api<{image:string}>('/api/integrations/waha/qr');setQr(result.image);setStatus('SCAN_QR_CODE');setNotice('QR Code pronto. No celular, abra WhatsApp → Aparelhos conectados → Conectar aparelho.');return}catch(e){if(!(e instanceof ApiError)||e.status!==425)throw e;setNotice('A sessão está iniciando. Aguardando o QR Code…');if(attempt<19)await new Promise(resolve=>window.setTimeout(resolve,1500));}}setNotice('');setError('A sessão foi iniciada, mas o QR Code ainda não ficou pronto. Aguarde alguns segundos e tente atualizar.');}catch(e){setNotice('');setQr('');setError(errorMessage(e))}finally{setSaving(false)}}
 useEffect(()=>{if(!qr)return;let stopped=false,busy=false;const refresh=async()=>{if(stopped||busy)return;busy=true;try{const latest=await api<{status:string}>('/api/integrations/waha/status');if(stopped)return;setStatus(latest.status);if(latest.status==='WORKING'){setQr('');setNotice('WhatsApp conectado com sucesso.');return;}if(latest.status==='FAILED'){setQr('');setNotice('');setError('A conexão do WhatsApp falhou. Atualize o QR Code para reiniciar a sessão e tente conectar novamente.');return;}if(latest.status==='SCAN_QR_CODE'){try{const image=await api<{image:string}>('/api/integrations/waha/qr');if(!stopped)setQr(image.image);}catch(e){if(e instanceof ApiError&&e.status===425)return;throw e;}}}catch(e){if(!stopped){setQr('');setNotice('');setError(errorMessage(e));}}finally{busy=false;}};const timer=window.setInterval(()=>void refresh(),10000);return()=>{stopped=true;window.clearInterval(timer)}},[qr]);
 async function saveBot(e:FormEvent){e.preventDefault();setSaving(true);try{const result=await api<BotConfig>('/api/whatsapp/bot-settings',{method:'PUT',body:JSON.stringify(bot)});setBot({...result,aiModel:bot.aiModel});setNotice('Configurações do bot salvas.')}catch(e){setError(errorMessage(e))}finally{setSaving(false)}}
 async function toggleTemplate(t:Template){try{await api(`/api/message-templates/${t.id}`,{method:'PATCH',body:JSON.stringify({active:!t.active})});await load()}catch(e){setError(errorMessage(e))}}
 async function saveTemplate(e:FormEvent){e.preventDefault();if(!templateDraft)return;try{if(templateDraft.id)await api(`/api/message-templates/${templateDraft.id}`,{method:'PATCH',body:JSON.stringify({title:templateDraft.title,body:templateDraft.body})});else await api('/api/message-templates',{method:'POST',body:JSON.stringify({title:templateDraft.title,category:templateDraft.category,body:templateDraft.body})});setTemplateDraft(null);setNotice('Modelo salvo.');await load()}catch(e){setError(errorMessage(e))}}
 async function deleteTemplate(t:Template){if(!window.confirm(`Excluir o modelo “${t.title}”?`))return;try{await api(`/api/message-templates/${t.id}`,{method:'DELETE'});await load()}catch(e){setError(errorMessage(e))}}
 async function resume(){try{await api(`/api/whatsapp/conversations/${phone}/resume`,{method:'PATCH',body:'{}'});await load()}catch(e){setError(errorMessage(e))}}
 const setField=<K extends keyof BotConfig>(key:K,value:BotConfig[K])=>setBot(current=>({...current,[key]:value}));
 return <div className="mx-auto grid min-w-0 max-w-5xl gap-5 pb-8">
  <header><h1 className="text-2xl font-bold">WhatsApp &amp; bot de agendamento</h1><p className="mt-1 max-w-3xl text-sm text-muted-foreground">O bot responde pelo número da arena. Quando o cliente pede uma pessoa, a automação pausa para a equipe assumir.</p></header>
  {error&&<p role="alert" className="rounded-md bg-red-50 p-3 text-sm text-red-700">{error}</p>}{notice&&<p role="status" className="rounded-md bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</p>}
  <nav className="flex flex-wrap gap-2 border-b pb-3" aria-label="Seções do WhatsApp">{([['config','Bot & configuração'],['services','Informações & automações'],['conversas','Conversas'],['modelos','Modelos de mensagem']] as const).map(([id,label])=><Button key={id} variant={tab===id?'default':'outline'} onClick={()=>setTab(id)}>{label}</Button>)}</nav>
  {loading?<div className="grid min-h-40 place-items-center"><LoaderCircle className="animate-spin"/></div>:<>
  {tab==='services'&&<WhatsAppServices editable={editable}/>}
  {tab==='config'&&<form className="grid gap-5" onSubmit={e=>void saveBot(e)}>
   {!config.aiConfigured&&<p role="status" className="rounded-md bg-amber-50 p-3 text-sm text-amber-900">O agente de IA ainda não está configurado. O fluxo guiado pode atender reservas; para ativar respostas em linguagem natural, o responsável pela hospedagem precisa definir OPENAI_API_KEY no ambiente seguro da API.</p>}
   <Card><CardHeader><CardTitle className="flex flex-wrap items-center gap-2 text-base"><Smartphone className="size-5 text-emerald-700"/>Conexão do número <Badge variant="outline">{status==='not_configured'?'não configurado':status==='WORKING'?'conectado':status==='SCAN_QR_CODE'?'aguardando leitura do QR':status==='STARTING'?'iniciando':status==='STOPPED'?'desconectado':status==='FAILED'?'falha na conexão':status==='unavailable'?'serviço indisponível':status}</Badge></CardTitle></CardHeader><CardContent className="grid gap-4">
    <p className="text-sm text-muted-foreground">Conecte o WhatsApp da arena escaneando o QR Code. O número continua funcionando no celular.</p>
    {!config.serviceConfigured&&<p role="status" className="rounded-md bg-amber-50 p-3 text-sm text-amber-900">O servidor WhatsApp ainda não está configurado. O responsável pela hospedagem precisa ativar a instância WAHA exclusiva do QuadrasFlow e definir suas variáveis de acesso e webhook. Depois disso, volte aqui para salvar a conexão.</p>}
    <div className="grid min-w-0 gap-2"><Label htmlFor="waha-session">Identificador da sessão</Label><div className="grid min-w-0 gap-2 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center"><Input id="waha-session" readOnly value={config.session||user?.company?.slug||''} placeholder="Gerado automaticamente para sua arena"/><Button type="button" className="w-full whitespace-nowrap sm:w-auto" disabled={!editable||saving||!config.serviceConfigured||status==='WORKING'} onClick={()=>void connectWhatsApp()}>{saving?<LoaderCircle className="animate-spin"/>:<QrCode/>}{saving?'Preparando…':status==='WORKING'?'WhatsApp conectado':config.session?'Atualizar QR Code':'Conectar WhatsApp'}</Button></div><p className="text-xs text-muted-foreground">Esse identificador é criado automaticamente; você não precisa editar ou salvar antes de conectar.</p></div>
    {notice&&<p role="status" aria-live="polite" className="text-sm text-muted-foreground">{notice}</p>}{qr&&<div className="flex flex-col items-center gap-2 rounded-xl border bg-white p-4 sm:flex-row"><img src={qr} alt="QR Code para conectar o WhatsApp" className="size-48 object-contain"/><p className="max-w-md text-sm text-muted-foreground">No celular, abra WhatsApp → Aparelhos conectados → Conectar aparelho e escaneie este código.</p></div>}{config.webhookUrl&&<details className="text-xs text-muted-foreground"><summary className="cursor-pointer">Detalhes técnicos da conexão</summary><p className="mt-2 break-all">Webhook: {config.webhookUrl}</p></details>}
   </CardContent></Card>
   <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Bot className="size-5 text-emerald-700"/>Bot automático</CardTitle></CardHeader><CardContent className="grid gap-5">
    <label className="flex cursor-pointer items-start gap-3"><input className="mt-1 size-4 accent-emerald-700" type="checkbox" disabled={!editable} checked={bot.enabled} onChange={e=>setField('enabled',e.target.checked)}/><span><strong className="text-sm">Bot ativo</strong><span className="block text-sm text-muted-foreground">{config.aiConfigured?'Agente de IA responde perguntas e conduz a reserva com os dados da arena.':'Agente de IA indisponível; o fluxo guiado continua ativo até configurar o provedor.'}</span></span></label>
    {config.aiConfigured&&<p className="text-xs text-muted-foreground">Modelo do agente: {bot.aiModel||'gpt-4.1-mini'}</p>}
    <div className="grid gap-2 rounded-lg border p-4"><Label htmlFor="arena-time-zone">Fuso horário da arena</Label><select id="arena-time-zone" className="h-10 w-full max-w-md rounded-md border bg-background px-3 text-sm" disabled={!editable} value={bot.timeZone} onChange={e=>setField('timeZone',e.target.value)}><option value="">Selecione o fuso da cidade</option>{['America/Noronha','America/Belem','America/Fortaleza','America/Recife','America/Maceio','America/Bahia','America/Santarem','America/Araguaina','America/Sao_Paulo','America/Campo_Grande','America/Cuiaba','America/Porto_Velho','America/Boa_Vista','America/Manaus','America/Eirunepe','America/Rio_Branco'].map(zone=><option key={zone} value={zone}>{zone.replace('America/','').replaceAll('_',' ')}</option>)}</select><p className="text-xs text-muted-foreground">Escolha o fuso IANA correspondente à cidade e UF da arena. O bot usa este horário para interpretar “hoje”, “amanhã” e os horários disponíveis.</p>{!bot.timeZone&&<p className="text-xs text-amber-700">Configure o fuso antes de usar o agendamento automático.</p>}</div>
    <div className="grid gap-3 rounded-lg border p-4"><label className="flex cursor-pointer items-start gap-3"><input className="mt-1 size-4 accent-emerald-700" type="checkbox" disabled={!editable} checked={bot.testMode} onChange={e=>setField('testMode',e.target.checked)}/><span><strong className="text-sm">Modo de teste</strong><span className="block text-sm text-muted-foreground">Quando ativado, o bot só responde aos números autorizados abaixo. As mensagens dos outros contatos são ignoradas.</span></span></label><div className="grid gap-2"><Label htmlFor="bot-test-phones">Números autorizados</Label><Textarea id="bot-test-phones" rows={3} maxLength={2000} disabled={!editable} value={bot.testPhones.join('\n')} onChange={e=>setField('testPhones',e.target.value.split(/[\n,;]/).map(value=>value.trim()).filter(Boolean))} placeholder="5511999999999"/><p className="text-xs text-muted-foreground">Um número por linha. Inclua o código do país, por exemplo 55 para o Brasil. Formatação com +, espaços, parênteses e hífens é aceita.</p></div></div>
    <div className="rounded-xl border p-4"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Fluxo de agendamento</p><div className="mt-3 flex flex-wrap items-center justify-center gap-x-3 gap-y-2">{flow.map(([name,color],i)=><div key={name} className="flex items-center gap-3"><span className={`rounded-full bg-muted px-3 py-2 text-xs font-semibold ${color}`}>{name}</span>{i<flow.length-1&&<span aria-hidden="true" className="text-muted-foreground">→</span>}</div>)}</div><p className="mt-3 text-xs text-muted-foreground">Hoje o bot coleta quadra, data, horário e duração; a reserva fica pendente de confirmação da arena.</p></div>
    <div className="grid gap-2"><Label htmlFor="bot-welcome">Pergunta do menu</Label><p className="text-xs text-muted-foreground">A mensagem inicial mostra as opções de agendar e falar com a equipe.</p><Textarea id="bot-welcome" rows={3} maxLength={500} disabled={!editable} value={bot.welcome} onChange={e=>setField('welcome',e.target.value)}/></div>
    <div className="rounded-xl border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-semibold">Opções extras do menu</h3><p className="text-xs text-muted-foreground">Crie respostas rápidas para valores, endereço ou regras.</p></div><Button type="button" size="sm" variant="outline" disabled={!editable||bot.menuOptions.length>=10} onClick={()=>setField('menuOptions',[...bot.menuOptions,{id:crypto.randomUUID(),label:'',response:''}])}><Plus/> Adicionar opção</Button></div><div className="mt-3 grid gap-3">{bot.menuOptions.map((option,index)=><div key={option.id} className="grid gap-3 rounded-lg bg-muted/40 p-3 sm:grid-cols-[.7fr_1.3fr_auto]"><div className="grid gap-1"><Label>Nome no menu</Label><Input maxLength={24} disabled={!editable} value={option.label} onChange={e=>setField('menuOptions',bot.menuOptions.map((o,i)=>i===index?{...o,label:e.target.value}:o))}/></div><div className="grid gap-1"><Label>Resposta do bot</Label><Textarea rows={2} maxLength={2000} disabled={!editable} value={option.response} onChange={e=>setField('menuOptions',bot.menuOptions.map((o,i)=>i===index?{...o,response:e.target.value}:o))}/></div><Button type="button" variant="ghost" size="icon" aria-label="Remover opção" disabled={!editable} onClick={()=>setField('menuOptions',bot.menuOptions.filter((_,i)=>i!==index))}><Trash2/></Button></div>)}</div></div>
   </CardContent></Card>
   <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><UserRound className="size-5 text-emerald-700"/>Quando o cliente pede um atendente</CardTitle></CardHeader><CardContent className="grid gap-4"><p className="rounded-lg bg-muted/60 p-3 text-sm text-muted-foreground">A automação pausa durante o atendimento humano. Em Informações & automações, escolha se a equipe deve liberar a retomada. O prazo abaixo só vale quando a retomada automática estiver habilitada.</p><div className="grid gap-2"><Label htmlFor="handoff-message">Mensagem de encaminhamento</Label><Textarea id="handoff-message" rows={3} maxLength={1000} disabled={!editable} value={bot.handoffMessage} onChange={e=>setField('handoffMessage',e.target.value)}/></div><div className="flex flex-wrap items-center gap-3"><Clock3 className="size-4"/><Label htmlFor="reactivate-hours">Retomar automação após</Label><Input id="reactivate-hours" className="w-24 bg-background" type="number" min={1} max={48} disabled={!editable} value={bot.reactivateAfterHours} onChange={e=>setField('reactivateAfterHours',Number(e.target.value))}/><span className="text-sm text-muted-foreground">horas sem mensagem</span></div></CardContent></Card>
   <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Clock3 className="size-5 text-emerald-700"/>Horário de atendimento humano</CardTitle></CardHeader><CardContent className="grid gap-4"><p className="text-sm text-muted-foreground">Esse horário vale quando o cliente pede um atendente. O bot de agendamento continua disponível.</p><div className="grid gap-4 sm:grid-cols-2"><div className="grid gap-2"><Label htmlFor="human-start">Início</Label><Input id="human-start" type="time" disabled={!editable} value={bot.humanStart} onChange={e=>setField('humanStart',e.target.value)}/></div><div className="grid gap-2"><Label htmlFor="human-end">Fim</Label><Input id="human-end" type="time" disabled={!editable} value={bot.humanEnd} onChange={e=>setField('humanEnd',e.target.value)}/></div></div><div className="grid gap-2"><Label htmlFor="outside-hours">Resposta fora do horário humano</Label><Textarea id="outside-hours" rows={2} maxLength={1000} disabled={!editable} value={bot.outsideHoursMessage} onChange={e=>setField('outsideHoursMessage',e.target.value)}/></div></CardContent></Card>
   <Card><CardHeader><CardTitle className="text-base">Pagamento para reservar</CardTitle></CardHeader><CardContent className="grid gap-4"><p className="text-sm text-muted-foreground">Escolha quanto o cliente paga antecipadamente. Sem cobrança, o agente não solicita nem envia Pix e a equipe confirma a reserva.</p><div className="grid gap-2"><Label htmlFor="payment-mode">Cobrança antecipada</Label><select id="payment-mode" className="h-10 w-full rounded-md border bg-background px-3 text-sm" disabled={!editable} value={bot.paymentMode} onChange={e=>setField("paymentMode",e.target.value as BotConfig["paymentMode"])}><option value="none">Sem Pix antecipado</option><option value="full">Valor integral</option><option value="percent">Percentual do valor</option><option value="fixed">Valor fixo</option></select></div>{bot.paymentMode==="percent"&&<div className="grid gap-2"><Label htmlFor="payment-percent">Percentual antecipado (%)</Label><Input id="payment-percent" className="max-w-40" type="number" min={1} max={100} step={1} required disabled={!editable} value={bot.paymentPercent} onChange={e=>setField("paymentPercent",Number(e.target.value))}/></div>}{bot.paymentMode==="fixed"&&<div className="grid gap-2"><Label htmlFor="payment-fixed">Valor antecipado (R$)</Label><Input id="payment-fixed" className="max-w-40" type="number" min={0.01} step={0.01} required disabled={!editable} value={bot.paymentFixedCents/100} onChange={e=>setField("paymentFixedCents",Math.round(Number(e.target.value)*100))}/><p className="text-xs text-muted-foreground">Se a reserva custar menos que o sinal, será cobrado somente o valor da reserva.</p></div>}</CardContent></Card>
   <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><CreditCard className="size-5 text-emerald-700"/>Confirmação e lembrete de pagamento</CardTitle></CardHeader><CardContent className="grid gap-4"><label className="flex items-start gap-3"><input type="checkbox" className="mt-1 size-4 accent-emerald-700" disabled={!editable} checked={bot.notifyPayment} onChange={e=>setField('notifyPayment',e.target.checked)}/><span><strong className="text-sm">Avisar quando o Pix for pago</strong><span className="block text-sm text-muted-foreground">Envia a confirmação após o Mercado Pago aprovar o pagamento.</span></span></label><label className="flex items-start gap-3"><input type="checkbox" className="mt-1 size-4 accent-emerald-700" disabled={!editable} checked={bot.remindUnpaid} onChange={e=>setField('remindUnpaid',e.target.checked)}/><span><strong className="text-sm">Lembrar quem gerou o Pix e não pagou</strong><span className="block text-sm text-muted-foreground">O lembrete depende da cobrança Pix estar vinculada à reserva e ainda pendente.</span></span></label><p className="text-xs text-muted-foreground">Os avisos de pagamento só funcionam quando o Mercado Pago está conectado.</p></CardContent></Card>
   <div className="flex justify-end"><Button disabled={!editable||saving}>{saving?<LoaderCircle className="animate-spin"/>:<Check/>} Salvar configurações</Button></div>
  </form>}
  {tab==='conversas'&&<div className="grid gap-4 xl:grid-cols-[.8fr_1.2fr]"><Card><CardHeader><CardTitle className="text-base">Conversas recentes</CardTitle></CardHeader><CardContent className="grid max-h-[520px] gap-1 overflow-auto">{conversations.length?conversations.map(c=><button key={c.phone} onClick={()=>void selectConversation(c.phone)} className={`rounded-lg border p-3 text-left ${phone===c.phone?'border-primary bg-emerald-50':''}`}><div className="flex justify-between gap-2 text-sm font-semibold"><span>{c.phone}</span><span className="text-[10px] font-normal text-muted-foreground">{formatDate(c.updated_at)}</span></div><p className="mt-1 truncate text-xs text-muted-foreground">{c.last_message||'Sem mensagens'}</p>{c.step==='human'&&<Badge className="mt-2" variant="secondary">Atendimento humano</Badge>}</button>):<p className="py-8 text-center text-sm text-muted-foreground">Ainda não há conversas.</p>}</CardContent></Card><Card><CardHeader><CardTitle className="text-base">{phone?`Conversa · ${phone}`:'Selecione uma conversa'}</CardTitle></CardHeader><CardContent className="grid gap-3">{phone?<><div className="grid max-h-[420px] gap-2 overflow-auto rounded-lg bg-muted/50 p-3">{messages.map((m,i)=><div key={`${m.created_at}-${i}`} className={`max-w-[85%] rounded-lg p-3 text-sm ${m.direction==='out'?'ml-auto bg-primary text-primary-foreground':'bg-card'}`}><p className="whitespace-pre-wrap break-words">{m.body}</p><span className="mt-1 block text-right text-[10px] opacity-70">{new Date(m.created_at).toLocaleString('pt-BR')}</span></div>)}</div><div className="flex justify-between"><Button size="sm" variant="outline" onClick={()=>void resume()}>Retomar automação</Button></div><form className="flex gap-2" onSubmit={e=>void send(e)}><Textarea aria-label="Mensagem" rows={2} maxLength={2000} value={reply} onChange={e=>setReply(e.target.value)} placeholder="Digite sua resposta"/><Button type="submit" size="icon" aria-label="Enviar" disabled={!reply.trim()}><Send/></Button></form></>:<p className="py-16 text-center text-sm text-muted-foreground">Escolha uma conversa para ver o histórico e responder.</p>}</CardContent></Card></div>}
  {tab==='modelos'&&<div className="grid gap-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-lg font-semibold">Modelos de mensagem</h2><p className="text-sm text-muted-foreground">Textos prontos enviados pelo bot ou pela equipe.</p></div><Button disabled={!editable} onClick={()=>setTemplateDraft({id:'',title:'',category:'personalizado',body:'',active:true})}><Plus/> Novo modelo</Button></div><div className="grid gap-3 md:grid-cols-2">{templates.map(t=><Card key={t.id}><CardHeader className="flex flex-row items-start justify-between gap-2 space-y-0"><div><CardTitle className="text-base">{t.title}</CardTitle><Badge variant="secondary" className="mt-2">{t.category}</Badge></div><div className="flex gap-1"><Button size="icon" variant="ghost" aria-label="Editar modelo" disabled={!editable} onClick={()=>setTemplateDraft({...t,body:t.body,active:Boolean(t.active)})}><Pencil/></Button><Button size="icon" variant="ghost" aria-label="Excluir modelo" disabled={!editable} onClick={()=>void deleteTemplate(t)}><Trash2/></Button></div></CardHeader><CardContent><p className="whitespace-pre-wrap break-words text-sm text-muted-foreground">{t.body}</p><Button className="mt-4" size="sm" variant={t.active?'secondary':'outline'} disabled={!editable} onClick={()=>void toggleTemplate(t)}>{t.active?'Ativo':'Inativo'}</Button></CardContent></Card>)}</div></div>}
  </>}
  {templateDraft&&<div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-black/50 p-4" role="dialog" aria-modal="true" aria-labelledby="template-title"><form className="my-auto grid max-h-[calc(100dvh-2rem)] w-full max-w-xl gap-4 overflow-y-auto rounded-xl border bg-background p-4 shadow-xl sm:p-5" onSubmit={e=>void saveTemplate(e)}><div><h2 id="template-title" className="text-lg font-semibold">{templateDraft.id?'Editar modelo':'Novo modelo'}</h2><p className="text-sm text-muted-foreground">Você pode usar variáveis como {'{arena_name}'}, {'{quadra}'}, {'{data}'}, {'{horario}'} e {'{valor}'}.</p></div><div className="grid gap-2"><Label htmlFor="template-name">Título</Label><Input id="template-name" required maxLength={80} value={templateDraft.title} onChange={e=>setTemplateDraft({...templateDraft,title:e.target.value})}/></div>{!templateDraft.id&&<div className="grid gap-2"><Label htmlFor="template-category">Categoria</Label><select id="template-category" className="h-10 rounded-md border bg-background px-3 text-sm" value={templateDraft.category} onChange={e=>setTemplateDraft({...templateDraft,category:e.target.value})}><option value="personalizado">Personalizado</option><option value="menu">Menu</option><option value="reserva_criada">Reserva criada</option><option value="reserva_confirmada">Reserva confirmada</option><option value="lembrete">Lembrete</option><option value="pagamento">Pagamento</option><option value="avaliacao">Avaliação</option></select></div>}<div className="grid gap-2"><Label htmlFor="template-body">Mensagem</Label><Textarea id="template-body" rows={7} required maxLength={2000} value={templateDraft.body} onChange={e=>setTemplateDraft({...templateDraft,body:e.target.value})}/><p className="text-xs text-muted-foreground">{templateDraft.body.length} caracteres</p></div><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setTemplateDraft(null)}>Cancelar</Button><Button type="submit"><Check/> Salvar modelo</Button></div></form></div>}
 </div>
}
